"""Trunk work, isometric holds, loaded carries and full-body conditioning movements."""

_SUPINE_CAMERA = "side view, camera low near floor level, athlete facing left with the head on the right, lying on the back"
_MAT = "an exercise mat on a plain gym floor"
_BAR_GRIP = "no held load; hands gripping a pull-up bar overhead with an overhand grip, shoulder-width apart"
_BAR_SETTING = "hanging from a fixed overhead pull-up bar on a plain gym floor, feet clear of the floor"
_WALK_CAMERA = "side view, camera at hip height, athlete facing left and walking to the left"
_WALK_SETTING = "a plain gym floor with open space ahead of the athlete"

EXERCISES = [
    {
        "name": "Plank",
        "aliases": [
            "plank",
            "planks",
            "front plank",
            "front planks",
            "forearm plank",
            "forearm planks",
            "elbow plank",
            "elbow planks",
            "low plank",
            "low planks",
            "prone plank",
            "plank hold",
            "plank holds",
            "front plank hold",
            "forearm plank hold",
            "elbow plank hold",
            "standard plank",
            "abdominal plank",
            "rkc plank",
            "hardstyle plank",
        ],
        "category": "core_and_carries",
        "camera": "side view, camera low near floor level, athlete facing left",
        "equipment": "no equipment",
        "setting": _MAT,
        "loop": "pingpong",
        "keyframes": [
            "kneeling on the mat on all fours with forearms flat on the mat, elbows directly under the shoulders, hips stacked above the knees, thighs vertical, toes tucked under",
            "hips shifting forward and down, knees still on the mat, torso and thighs forming a shallow angle, forearms flat, elbows under the shoulders, eyes on the mat",
            "knees lifting a hand's width off the mat, weight on the forearms and toes, hips slightly piked upward, legs bent about 30 degrees",
            "knees straightening, hips still slightly above the shoulder-to-heel line, weight on forearms and toes, head neutral looking at the mat",
            "hips settling down almost level with the shoulders, legs straight, feet together, forearms flat with palms down, shoulders directly over the elbows",
            "full forearm plank: body a straight line from head to heels, elbows under the shoulders, forearms flat, hips level, legs straight, toes tucked, eyes on the mat",
        ],
        "cue": "Squeeze glutes, ribs down, straight line head to heels.",
        "notes": "",
    },
    {
        "name": "Side Plank",
        "aliases": [
            "side planks",
            "side plank hold",
            "side plank holds",
            "side bridge",
            "side bridges",
            "lateral plank",
            "lateral planks",
            "forearm side plank",
            "elbow side plank",
            "side elbow plank",
            "side plank on forearm",
            "side plank on elbow",
        ],
        "category": "core_and_carries",
        "camera": "front view, camera low near floor level, athlete lying on the right side facing the camera, head on the left",
        "equipment": "no equipment",
        "setting": _MAT,
        "loop": "pingpong",
        "keyframes": [
            "lying on the right side, right forearm flat on the mat with the elbow under the shoulder, hips resting on the mat, legs straight and stacked, left hand on the hip",
            "hips just lifting off the mat, weight moving onto the right forearm and the outside edge of the right foot, legs straight and stacked, left hand on the hip",
            "hips a hand's width off the mat, body still slightly sagging at the waist, right elbow under the shoulder, feet stacked, left hand on the hip",
            "hips halfway to full height, torso and legs nearly in line, weight on the right forearm and right foot, left hand on the hip, head in line with the spine",
            "hips almost fully lifted, body nearly a straight line from head to feet, left arm beginning to extend straight up toward the ceiling",
            "full side plank: body a straight line from head to feet, hips high, right elbow under the shoulder, feet stacked, left arm pointing straight up at the ceiling",
        ],
        "cue": "Stack the feet, lift the hips, stay long.",
        "notes": "",
    },
    {
        "name": "Hollow Hold",
        "aliases": [
            "hollow holds",
            "hollow",
            "hollow body hold",
            "hollow body holds",
            "hollow body",
            "hollow position",
            "hollow position hold",
            "hollow body position",
        ],
        "category": "core_and_carries",
        "camera": _SUPINE_CAMERA,
        "equipment": "no equipment",
        "setting": _MAT,
        "loop": "pingpong",
        "keyframes": [
            "lying flat on the back on the mat, legs straight and together on the mat, arms straight overhead resting on the mat beside the ears, chin neutral",
            "lower back pressing into the mat, head and shoulders lifting slightly, arms straight overhead just off the mat, heels lifting a few centimetres, legs straight",
            "shoulder blades off the mat, arms straight overhead at about 30 degrees to the floor, legs straight with the heels a hand's width above the mat",
            "torso curled further so the shoulders are well off the mat, arms overhead by the ears at about 40 degrees, legs straight and raised about 20 degrees",
            "upper back off the mat with the lower back flat and pressed down, arms straight by the ears pointing forward and up, legs straight and raised about 30 degrees",
            "full hollow position: body a shallow banana shape, lower back pressed into the mat, shoulders and legs raised, arms straight beside the ears, legs straight, toes pointed",
        ],
        "cue": "Lower back glued to the floor, ribs down.",
        "notes": "",
    },
    {
        "name": "Dead Bug",
        "aliases": [
            "dead bugs",
            "deadbug",
            "deadbugs",
            "alternating dead bug",
            "alternating dead bugs",
            "supine dead bug",
        ],
        "category": "core_and_carries",
        "camera": _SUPINE_CAMERA,
        "equipment": "no equipment",
        "setting": _MAT,
        "loop": "pingpong",
        "keyframes": [
            "lying on the back with both arms straight up pointing at the ceiling, hips and knees bent 90 degrees so the shins are parallel to the mat, lower back flat",
            "right arm starting to lower toward the mat overhead, left knee beginning to straighten and the left foot moving away, left arm and right leg still in the start position",
            "right arm at about 45 degrees above the head, left leg extended about halfway with the knee bent 45 degrees, right leg still bent 90 degrees, left arm vertical",
            "right arm nearly horizontal overhead, left leg almost straight with the heel about 30 centimetres above the mat, lower back pressed flat, right knee bent 90 degrees",
            "right arm horizontal just above the mat beside the ear, left leg straight and hovering a hand's width above the mat, left arm and right leg unchanged",
            "end position: right arm straight overhead just above the mat, left leg straight and hovering above the mat, left arm vertical, right knee bent 90 degrees, lower back flat",
        ],
        "cue": "Press the low back down, reach opposite arm and leg.",
        "notes": "",
    },
    {
        "name": "Bird Dog",
        "aliases": [
            "bird dogs",
            "birddog",
            "birddogs",
            "bird dog hold",
            "bird dog holds",
            "alternating bird dog",
            "alternating bird dogs",
            "quadruped bird dog",
            "quadruped arm leg raise",
            "quadruped opposite arm leg raise",
            "quadruped opposite arm and leg raise",
            "opposite arm and leg raise",
        ],
        "category": "core_and_carries",
        "camera": "side view, camera slightly above hip height, athlete facing left on hands and knees",
        "equipment": "no equipment",
        "setting": _MAT,
        "loop": "pingpong",
        "keyframes": [
            "on hands and knees on the mat, hands directly under the shoulders, knees under the hips, back flat, head neutral looking down at the mat",
            "left hand lifting off the mat with the arm bent, right foot lifting off the mat with the knee bent, back flat, hips level",
            "left arm reaching forward at about 45 degrees below horizontal, right leg extending back with the knee bent 45 degrees, hips level, back flat",
            "left arm nearly horizontal reaching forward, right leg nearly straight reaching back with the foot below hip height, back flat, neck neutral",
            "left arm horizontal at shoulder height, right leg almost fully extended just below the level of the hips, torso still, back flat",
            "end position: left arm straight forward at shoulder height and right leg straight back at hip height, forming one line with the torso, hips level, supporting hand and knee unchanged",
        ],
        "cue": "Reach long, hips level, keep the back flat.",
        "notes": "",
    },
    {
        "name": "Pallof Press",
        "aliases": [
            "pallof presses",
            "pallof",
            "paloff press",
            "palof press",
            "pallof hold",
            "cable pallof press",
            "band pallof press",
            "banded pallof press",
            "standing pallof press",
            "kneeling pallof press",
            "half kneeling pallof press",
            "tall kneeling pallof press",
            "anti rotation press",
            "anti rotation hold",
        ],
        "category": "core_and_carries",
        "camera": "three-quarter front view, camera at chest height, athlete facing the camera with the cable running out to the right edge of the panel",
        "equipment": "a cable machine with the pulley set at chest height, a single D-handle held in both hands, the cable pulling sideways toward the athlete's right",
        "setting": "a cable station on a plain gym floor, the athlete standing side-on to the pulley",
        "loop": "pingpong",
        "keyframes": [
            "standing tall with feet shoulder-width apart, knees soft, both hands clasped around the handle held against the sternum, elbows tucked at the sides, cable taut to the right",
            "hands pressing the handle a hand's width away from the chest, elbows bending less, shoulders square to the camera, torso still, feet planted",
            "handle about halfway out, elbows bent 90 degrees, forearms horizontal, handle in line with the middle of the chest, torso square and upright",
            "handle three quarters of the way out, elbows nearly straight, arms at chest height, cable still running horizontally to the right, hips square",
            "arms almost fully extended straight out in front of the sternum at shoulder height, handle in the midline of the body, shoulders level",
            "end position: arms fully locked out straight ahead at chest height, handle centred in front of the sternum, torso square to the camera, feet planted, cable taut to the right",
        ],
        "cue": "Press straight out, don't let the cable turn you.",
        "notes": "",
    },
    {
        "name": "Farmer's Carry",
        "aliases": [
            "farmers carry",
            "farmer carry",
            "farmers carries",
            "farmer carries",
            "farmer's carries",
            "farmers walk",
            "farmer walk",
            "farmer's walk",
            "farmers walks",
            "farmer walks",
            "farmer's walks",
            "farmers",
            "dumbbell farmers carry",
            "dumbbell farmer carry",
            "dumbbell farmers walk",
            "db farmers carry",
            "db farmer carry",
            "db farmers walk",
            "kettlebell farmers carry",
            "kettlebell farmer carry",
            "kettlebell farmers walk",
            "kb farmers carry",
            "kb farmer carry",
            "kb farmers walk",
            "trap bar carry",
            "trap bar farmers carry",
            "trap bar farmers walk",
            "loaded carry",
            "loaded carries",
            "weighted carry",
            "weighted carries",
            "dumbbell carry",
            "kettlebell carry",
            "double kettlebell carry",
            "double kb carry",
        ],
        "category": "core_and_carries",
        "camera": _WALK_CAMERA,
        "equipment": "a heavy kettlebell held in each hand hanging at arm's length at the sides, neutral grip, shoulders back",
        "setting": _WALK_SETTING,
        "loop": "cycle",
        "keyframes": [
            "walking tall with the kettlebells at the sides, left foot ahead landing heel first, right foot behind on the floor, torso upright, arms straight, shoulders back",
            "left foot flat with weight over it, right heel lifting off the floor behind, torso upright, arms straight, kettlebells steady at the sides",
            "standing on the left leg, right foot swinging forward past the left ankle just above the floor, knees soft, torso tall, kettlebells at the sides",
            "right foot ahead landing heel first, left foot behind on the floor, torso upright, arms straight, shoulders back, kettlebells hanging at the sides",
            "right foot flat with weight over it, left heel lifting off the floor behind, torso tall, kettlebells at the sides, eyes forward",
            "standing on the right leg, left foot swinging forward past the right ankle just above the floor, knees soft, torso tall, kettlebells at the sides",
        ],
        "cue": "Stand tall, shoulders back, short quick steps.",
        "notes": "",
    },
    {
        "name": "Suitcase Carry",
        "aliases": [
            "suitcase carries",
            "suitcase walk",
            "suitcase walks",
            "suitcase hold",
            "single arm farmers carry",
            "single arm farmer carry",
            "single arm farmers walk",
            "one arm farmers carry",
            "one arm farmer carry",
            "one arm farmers walk",
            "one handed farmers carry",
            "unilateral farmers carry",
            "unilateral carry",
            "single arm carry",
            "one arm carry",
            "one handed carry",
            "dumbbell suitcase carry",
            "db suitcase carry",
            "kettlebell suitcase carry",
            "kb suitcase carry",
            "single arm kettlebell carry",
            "single arm dumbbell carry",
        ],
        "category": "core_and_carries",
        "camera": _WALK_CAMERA,
        "equipment": "a single heavy kettlebell held in the right hand hanging at arm's length at the side, the left arm hanging free at the side",
        "setting": _WALK_SETTING,
        "loop": "cycle",
        "keyframes": [
            "walking tall with the kettlebell in the right hand at the side, left arm hanging free, left foot ahead landing heel first, right foot behind, torso vertical, shoulders level",
            "left foot flat with weight over it, right heel lifting off the floor behind, torso vertical and shoulders level, kettlebell steady beside the right thigh",
            "standing on the left leg, right foot swinging forward past the left ankle just above the floor, kettlebell at the right side, left arm relaxed",
            "right foot ahead landing heel first, left foot behind on the floor, torso vertical, shoulders level, kettlebell hanging beside the right thigh",
            "right foot flat with weight over it, left heel lifting off the floor behind, torso vertical, left arm hanging free, kettlebell at the right side",
            "standing on the right leg, left foot swinging forward past the right ankle just above the floor, shoulders level, kettlebell steady at the right side",
        ],
        "cue": "Stay tall and level, don't lean toward the weight.",
        "notes": "",
    },
    {
        "name": "Hanging Leg Raise",
        "aliases": [
            "hanging leg raises",
            "hanging straight leg raise",
            "hanging straight leg raises",
            "straight leg hanging leg raise",
            "hlr",
            "hlrs",
            "toes to bar",
            "t2b",
            "ttb",
            "bar leg raise",
            "bar leg raises",
            "hanging leg lift",
            "hanging leg lifts",
        ],
        "category": "core_and_carries",
        "camera": "side view, camera at chest height, athlete facing left",
        "equipment": _BAR_GRIP,
        "setting": _BAR_SETTING,
        "loop": "pingpong",
        "keyframes": [
            "dead hang from the bar with arms straight, body vertical, legs straight and together, toes pointed toward the floor, shoulders slightly engaged",
            "legs starting to lift with the knees straight, feet about 20 degrees forward of vertical, arms straight, torso still vertical",
            "legs straight and raised to about 45 degrees below horizontal, pelvis beginning to tilt back, arms straight, head neutral",
            "legs straight and parallel to the floor forming an L shape with the torso, arms straight, toes pointed forward",
            "legs straight and raised above horizontal, hips curling so the pelvis tilts back and the lower back rounds slightly, arms straight",
            "end position: legs straight and raised high with the feet near chest height, pelvis curled up, arms straight, body folded into a tight V shape",
        ],
        "cue": "Curl the pelvis up, not just the legs.",
        "notes": "",
    },
    {
        "name": "Ab Wheel Rollout",
        "aliases": [
            "ab wheel rollouts",
            "ab wheel roll out",
            "ab wheel roll outs",
            "ab wheel",
            "ab roller",
            "ab roller rollout",
            "ab rollout",
            "ab rollouts",
            "ab roll out",
            "ab roll outs",
            "wheel rollout",
            "wheel rollouts",
            "rollout",
            "rollouts",
            "kneeling rollout",
            "kneeling rollouts",
            "kneeling ab wheel rollout",
            "kneeling ab wheel",
            "barbell rollout",
            "barbell rollouts",
        ],
        "category": "core_and_carries",
        "camera": "side view, camera low near floor level, athlete facing left",
        "equipment": "an ab wheel with a handle on each side, both hands gripping the handles with the wheel on the floor",
        "setting": "an exercise mat on a plain gym floor, knees on the mat",
        "loop": "pingpong",
        "keyframes": [
            "kneeling upright on the mat with the wheel on the floor directly under the shoulders, arms straight and vertical, hips bent about 90 degrees, back flat",
            "wheel rolled a short way forward, arms straight angled slightly ahead, hips opening to about 120 degrees, torso leaning forward, knees on the mat",
            "wheel about halfway out, arms straight at 45 degrees to the floor, body a straight line from knees to shoulders angled about 45 degrees, hips extended",
            "wheel further out, arms straight at about 30 degrees to the floor, body straight from knees to hands, torso close to the mat, ribs tucked",
            "wheel almost fully extended, arms nearly parallel to the floor beside the ears, body straight from knees to hands, chest just above the mat",
            "end position: arms fully extended overhead nearly parallel to the floor, wheel far ahead, body a straight line from knees to hands hovering just above the mat",
        ],
        "cue": "Tuck the ribs, roll out as far as control allows.",
        "notes": "",
    },
    {
        "name": "Cable Crunch",
        "aliases": [
            "cable crunches",
            "kneeling cable crunch",
            "kneeling cable crunches",
            "rope crunch",
            "rope crunches",
            "cable rope crunch",
            "cable rope crunches",
            "rope cable crunch",
            "kneeling rope crunch",
            "kneeling rope crunches",
            "cable ab crunch",
            "cable ab crunches",
            "kneeling crunch",
            "kneeling crunches",
            "weighted cable crunch",
            "cable kneeling crunch",
        ],
        "category": "core_and_carries",
        "camera": "side view, camera at hip height, athlete facing left toward the cable stack",
        "equipment": "a cable machine with a rope attachment on the high pulley, the rope held with both hands beside the temples, elbows bent",
        "setting": "a cable station on a plain gym floor, the athlete kneeling on a mat facing the weight stack",
        "loop": "pingpong",
        "keyframes": [
            "kneeling upright on the mat facing the stack, hips bent slightly, torso tall with the spine long, rope held beside the temples, elbows pointing down",
            "upper back starting to round, chin tucking toward the chest, elbows moving slightly down, hips staying still, rope held at the head",
            "torso curled about 30 degrees forward from the ribs, elbows pointing toward the thighs, hips fixed, knees on the mat",
            "torso curled halfway down, spine rounded, elbows approaching the mid thighs, hips still at the same angle, rope beside the temples",
            "torso curled further, elbows near the knees, forehead approaching the thighs, hips fixed, spine fully rounded, knees on the mat",
            "bottom position: torso fully crunched with the spine rounded, elbows touching the mid thighs, forehead near the knees, hips still bent at the same angle",
        ],
        "cue": "Round the spine, pull the ribs to the hips.",
        "notes": "",
    },
    {
        "name": "Russian Twist",
        "aliases": [
            "russian twists",
            "seated russian twist",
            "seated russian twists",
            "weighted russian twist",
            "weighted russian twists",
            "medicine ball russian twist",
            "medicine ball russian twists",
            "med ball russian twist",
            "med ball russian twists",
            "plate russian twist",
            "plate russian twists",
            "dumbbell russian twist",
            "dumbbell russian twists",
            "db russian twist",
            "kettlebell russian twist",
            "kettlebell russian twists",
            "kb russian twist",
            "seated twist",
            "seated twists",
            "seated trunk twist",
            "seated torso twist",
        ],
        "category": "core_and_carries",
        "camera": "three-quarter front view, camera at chest height, athlete facing the camera, seated on the mat",
        "equipment": "a medicine ball held with both hands in front of the chest, arms bent",
        "setting": _MAT,
        "loop": "pingpong",
        "keyframes": [
            "seated on the mat with the torso leaning back about 45 degrees, knees bent, heels lightly touching the floor, both hands holding the ball beside the left hip near the mat",
            "torso rotated about halfway back toward centre, ball held over the left thigh, arms bent, knees bent, heels on the floor",
            "torso nearly square to the camera, ball in front of the chest slightly to the left, torso leaning back 45 degrees, knees bent",
            "torso nearly square to the camera, ball in front of the chest slightly to the right, torso leaning back 45 degrees, heels lightly on the floor",
            "torso rotated about halfway to the right, ball held over the right thigh, arms bent, knees bent, torso still leaning back",
            "end position: torso rotated fully to the right, ball held beside the right hip close to the mat, arms bent, knees bent, torso leaning back 45 degrees",
        ],
        "cue": "Rotate the ribs, not just the arms.",
        "notes": "",
    },
    {
        "name": "Back Extension",
        "aliases": [
            "back extensions",
            "hyperextension",
            "hyperextensions",
            "hyper extension",
            "hyper extensions",
            "hypers",
            "hyper",
            "45 degree back extension",
            "45 degree back extensions",
            "45 degree hyperextension",
            "45 degree hyperextensions",
            "45 degree hyper",
            "roman chair back extension",
            "roman chair hyperextension",
            "roman chair extension",
            "bench back extension",
            "lower back extension",
            "lower back extensions",
            "ghd back extension",
            "ghd back extensions",
            "ghd hip extension",
            "ghd hip extensions",
            "weighted back extension",
            "weighted back extensions",
        ],
        "category": "core_and_carries",
        "camera": "side view, camera at hip height, athlete facing left",
        "equipment": "no held load; hands crossed over the chest, ankles hooked under the padded rollers of the bench",
        "setting": "a 45-degree back extension bench on a plain gym floor, the hip pad just below the hip crease",
        "loop": "pingpong",
        "keyframes": [
            "bottom position: hips folded 90 degrees over the pad, torso hanging straight down toward the floor, head neutral, arms crossed over the chest, legs straight, ankles hooked",
            "torso raised about 20 degrees from vertical, hips beginning to extend, back flat, arms crossed, legs straight against the pad",
            "torso at about 45 degrees to the floor, hips half extended, back flat, glutes engaged, arms crossed over the chest",
            "torso about 30 degrees below the line of the legs, hips opening further, back flat, head in line with the spine",
            "torso almost in line with the legs, hips nearly fully extended, back flat, arms crossed, shoulders back, ankles hooked",
            "top position: body a straight line from head to heels along the 45-degree pad, hips fully extended, back flat, arms crossed over the chest",
        ],
        "cue": "Hinge at the hips, squeeze the glutes at the top.",
        "notes": "",
    },
    {
        "name": "Turkish Get-up",
        "aliases": [
            "turkish get ups",
            "turkish getup",
            "turkish getups",
            "tgu",
            "tgus",
            "get up",
            "get ups",
            "getup",
            "getups",
            "kettlebell turkish get up",
            "kettlebell turkish getup",
            "kb turkish get up",
            "kb tgu",
            "kettlebell get up",
            "kettlebell getup",
            "kb get up",
            "kb getup",
            "turkish get up with kettlebell",
            "dumbbell turkish get up",
            "db turkish get up",
        ],
        "category": "core_and_carries",
        "camera": "side view, camera at hip height, athlete facing left, lying with the head on the right at the start",
        "equipment": "a single kettlebell held in the right hand, arm locked out straight with the bell resting on the back of the forearm",
        "setting": _MAT,
        "loop": "cycle",
        "keyframes": [
            "lying on the back, kettlebell locked out in the right hand straight above the shoulder, right knee bent with the foot flat, left leg straight, left arm on the mat at 45 degrees",
            "rolled up onto the left elbow, torso propped at about 45 degrees, right arm still locked out with the bell overhead, right foot flat, left leg straight on the mat",
            "up on the straight left hand, hips lifted off the mat into a bridge from the left hand to the right foot, left leg straight, bell locked out overhead",
            "left leg swept back under the body into a half-kneeling position, left knee on the mat, right foot flat in front, torso upright, bell locked out overhead",
            "standing tall with feet hip-width apart, right arm locked out with the kettlebell overhead, left arm hanging at the side, eyes forward",
            "stepping back onto the left knee into a half-kneeling position, torso hinging sideways so the left hand reaches down to the mat, bell still overhead",
            "seated on the mat with the left hand flat on the floor behind the hips, right knee bent with the foot flat, left leg straight, bell locked out overhead",
            "lowered onto the left elbow with the torso at about 45 degrees, right knee bent, left leg straight on the mat, bell still locked out above the right shoulder",
        ],
        "cue": "Eyes on the bell, arm locked, move slowly.",
        "notes": "The kettlebell arm stays locked out straight and vertical in every panel, with the bell above the shoulder.",
    },
    {
        "name": "Burpee",
        "aliases": [
            "burpees",
            "full burpee",
            "full burpees",
            "burpee with push up",
            "burpees with push up",
            "chest to floor burpee",
            "chest to floor burpees",
            "chest to ground burpee",
            "chest to ground burpees",
            "standard burpee",
            "standard burpees",
            "bodyweight burpee",
            "bodyweight burpees",
        ],
        "category": "core_and_carries",
        "camera": "side view, camera at hip height, athlete facing left",
        "equipment": "no equipment",
        "setting": "a plain gym floor",
        "loop": "cycle",
        "keyframes": [
            "standing tall with feet hip-width apart, arms hanging at the sides, knees straight, eyes forward, weight even on both feet",
            "crouched in a deep squat with both hands flat on the floor just in front of the feet, knees fully bent, hips low, heels lifting",
            "high plank: hands flat under the shoulders, arms locked, legs kicked straight back onto the toes, body a straight line from head to heels",
            "bottom of the push-up: chest and thighs touching the floor, elbows bent and tucked, hands flat beside the chest, legs straight, toes tucked",
            "feet jumped forward back beside the hands into a deep crouch, hips low, knees fully bent, hands still flat on the floor, chest up",
            "jumping straight up with both feet off the floor, hips and knees fully extended, arms straight overhead, body vertical",
        ],
        "cue": "Chest to floor, jump tall, keep breathing.",
        "notes": "",
    },
    {
        "name": "Mountain Climber",
        "aliases": [
            "mountain climbers",
            "mtn climber",
            "mtn climbers",
            "alternating mountain climber",
            "alternating mountain climbers",
            "fast mountain climbers",
            "slow mountain climbers",
            "plank runners",
            "plank runs",
            "running plank",
        ],
        "category": "core_and_carries",
        "camera": "side view, camera low near floor level, athlete facing left",
        "equipment": "no equipment",
        "setting": "a plain gym floor",
        "loop": "cycle",
        "keyframes": [
            "high plank with hands flat under the shoulders and arms locked, right knee driven forward under the chest with the foot off the floor, left leg straight back on the toes, hips level",
            "right foot travelling back toward the hips and the left foot lifting off the floor, both feet momentarily off the floor, hands planted, hips level",
            "right foot landing back on its toes with the leg straight, left knee halfway forward under the hips, arms locked, back flat",
            "left knee driven fully forward under the chest with the foot off the floor, right leg straight back on the toes, hands planted under the shoulders, hips level",
            "left foot travelling back toward the hips and the right foot lifting off the floor, both feet momentarily off the floor, hands planted, hips level",
            "left foot landing back on its toes with the leg straight, right knee halfway forward under the hips, arms locked, back flat",
        ],
        "cue": "Hips low, hands planted, drive the knees fast.",
        "notes": "",
    },
    {
        "name": "Copenhagen Plank",
        "aliases": [
            "copenhagen planks",
            "copenhagen",
            "copenhagen plank hold",
            "copenhagen hold",
            "copenhagen adduction",
            "copenhagen adductor plank",
            "copenhagen adductor exercise",
            "copenhagen side plank",
            "adductor plank",
            "adductor side plank",
            "adductor plank on bench",
        ],
        "category": "core_and_carries",
        "camera": "front view, camera low near floor level, athlete lying on the right side facing the camera, head on the left and the bench on the right",
        "equipment": "no held load; the top left foot and ankle resting on top of a flat bench, the bottom right leg beneath the bench",
        "setting": "a flat bench on a plain gym floor beside an exercise mat, the athlete's feet toward the bench",
        "loop": "pingpong",
        "keyframes": [
            "lying on the right side with the right forearm on the mat, elbow under the shoulder, left ankle resting on top of the bench, right leg bent beneath the bench, hips on the mat",
            "hips just lifting off the mat, weight moving onto the right forearm and the left ankle on the bench, right knee still bent under the bench, left hand on the hip",
            "hips a hand's width off the mat, right leg straightening beneath the bench, torso still slightly sagging, left leg straight on the bench",
            "hips halfway up, body approaching a straight line from shoulders to the left foot, right leg straight and hovering below the bench",
            "hips almost fully raised, body nearly straight from head to the left foot, right leg straight and lifting toward the underside of the bench",
            "full Copenhagen plank: body a straight line from head to the left foot on the bench, hips high, right leg straight with the inner thigh pressed up against the underside of the bench",
        ],
        "cue": "Lift the hips, squeeze the legs together.",
        "notes": "",
    },
    {
        "name": "Hanging Knee Raise",
        "aliases": [
            "hanging knee raises",
            "hanging knee tuck",
            "hanging knee tucks",
            "hanging knee up",
            "hanging knee ups",
            "hanging knee lift",
            "hanging knee lifts",
            "hanging tuck",
            "hanging tucks",
            "hkr",
            "bar knee raise",
            "bar knee raises",
            "bent knee hanging leg raise",
            "bent knee hanging leg raises",
            "hanging bent knee raise",
            "hanging bent knee leg raise",
        ],
        "category": "core_and_carries",
        "camera": "side view, camera at chest height, athlete facing left",
        "equipment": _BAR_GRIP,
        "setting": _BAR_SETTING,
        "loop": "pingpong",
        "keyframes": [
            "dead hang from the bar with arms straight, body vertical, legs straight and together, toes pointed toward the floor, shoulders slightly engaged",
            "knees beginning to bend and lift forward, feet trailing slightly behind the knees, arms straight, torso still vertical",
            "knees bent about 90 degrees and raised to about 45 degrees below horizontal, shins hanging down, arms straight, torso vertical",
            "thighs parallel to the floor with the knees bent 90 degrees, shins vertical, arms straight, torso vertical, head neutral",
            "knees rising above hip height toward the chest, pelvis beginning to curl back, arms straight, lower back rounding slightly",
            "end position: knees pulled up tight to the chest, pelvis curled up, thighs against the torso, arms straight, feet tucked under the hips",
        ],
        "cue": "Knees to chest, curl the hips, no swinging.",
        "notes": "",
    },
    {
        "name": "Sit-up",
        "aliases": [
            "situp",
            "situps",
            "sit ups",
            "abmat sit up",
            "abmat sit ups",
            "abmat situp",
            "abmat situps",
            "ab mat sit up",
            "ab mat sit ups",
            "full sit up",
            "full sit ups",
            "butterfly sit up",
            "butterfly sit ups",
            "weighted sit up",
            "weighted sit ups",
            "bodyweight sit up",
            "bodyweight sit ups",
            "anchored sit up",
            "anchored sit ups",
            "floor sit up",
            "floor sit ups",
        ],
        "category": "core_and_carries",
        "camera": _SUPINE_CAMERA,
        "equipment": "no equipment",
        "setting": _MAT,
        "loop": "pingpong",
        "keyframes": [
            "lying flat on the back with knees bent about 90 degrees, feet flat on the mat, hands crossed over the chest, head resting on the mat",
            "chin tucking, head and shoulders lifting just off the mat, upper back starting to curl, hands on the chest, feet flat",
            "torso curled up to about 30 degrees from the mat, shoulder blades off the floor, hands crossed on the chest, knees bent",
            "torso at about 55 degrees from the mat, lower back leaving the mat, feet flat, hands on the chest, knees bent",
            "torso nearly upright at about 75 degrees, chest moving toward the knees, feet flat, hands crossed on the chest",
            "top position: sitting upright with the torso leaning slightly forward over the thighs, chest near the knees, feet flat, hands crossed over the chest",
        ],
        "cue": "Curl up rib by rib, control the way down.",
        "notes": "",
    },
    {
        "name": "Reverse Crunch",
        "aliases": [
            "reverse crunches",
            "lying reverse crunch",
            "lying reverse crunches",
            "reverse ab crunch",
            "reverse ab crunches",
            "reverse curl up",
            "reverse curl ups",
            "hip curl",
            "hip curls",
        ],
        "category": "core_and_carries",
        "camera": _SUPINE_CAMERA,
        "equipment": "no equipment",
        "setting": _MAT,
        "loop": "pingpong",
        "keyframes": [
            "lying on the back with arms flat on the mat at the sides, palms down, hips and knees bent 90 degrees so the shins are parallel to the mat, head down",
            "knees starting to draw toward the chest, tailbone beginning to curl up off the mat, arms pressing into the mat, head down",
            "hips lifting a hand's width off the mat, knees over the chest, shins still parallel to the floor, lower back rounding",
            "hips and lower back curled well off the mat, knees above the chest, feet over the face, arms flat at the sides",
            "hips raised high with the knees close to the chest, weight on the upper back and arms, shins angled toward the ceiling",
            "top position: hips lifted high off the mat with the knees tucked tight to the chest, tailbone pointing up, upper back and arms on the mat, head down",
        ],
        "cue": "Curl the hips up, don't swing the legs.",
        "notes": "",
    },
    {
        "name": "Bear Crawl",
        "aliases": [
            "bear crawls",
            "bear crawling",
            "forward bear crawl",
            "forward bear crawls",
            "bear crawl forward",
            "bear walk",
            "bear walks",
            "quadruped crawl",
            "quadruped crawls",
        ],
        "category": "core_and_carries",
        "camera": "side view, camera low near floor level, athlete facing left and crawling to the left",
        "equipment": "no equipment",
        "setting": _WALK_SETTING,
        "loop": "cycle",
        "keyframes": [
            "bear position: on hands and toes with the knees bent 90 degrees hovering just above the floor, hands under the shoulders, back flat and parallel to the floor",
            "right hand and left foot lifted off the floor and moving forward, weight on the left hand and right foot, back flat, knees low",
            "right hand planted a short step ahead and left foot planted forward under the hip, body slightly stretched, knees still hovering low",
            "body settled back into the bear position over all four points, knees hovering just above the floor, back flat, head neutral",
            "left hand and right foot lifted off the floor and moving forward, weight on the right hand and left foot, back flat, knees low",
            "left hand planted a short step ahead and right foot planted forward under the hip, body slightly stretched, knees hovering just above the floor",
        ],
        "cue": "Knees an inch off the floor, back flat.",
        "notes": "",
    },
]
