EXERCISES = [
    {
        "name": "Back Squat",
        "aliases": ["barbell back squat", "squat", "high bar squat", "low bar squat", "barbell squat"],
        "category": "lower_body",
        "camera": "side view, camera at hip height, athlete facing left",
        "equipment": "a loaded barbell with round plates resting across the upper back, hands gripping the bar just outside the shoulders",
        "setting": "inside a squat rack on a plain gym floor",
        "loop": "pingpong",
        "keyframes": [
            "standing fully upright with the barbell on the upper back, feet shoulder-width apart, knees locked, chest up, eyes forward",
            "hips just starting to travel back and down, knees bent about 20 degrees, torso tilted slightly forward, bar still over midfoot",
            "halfway down, knees bent about 60 degrees, thighs at 45 degrees to the floor, torso leaning forward, bar directly over midfoot",
            "thighs parallel to the floor, knees tracking over the toes, torso leaning forward, heels flat, bar over midfoot",
            "just below parallel, hips slightly lower than the knees, knees bent about 110 degrees, chest still up",
            "bottom position: deep squat with hips low and knees fully bent, heels flat, torso angle matching the shins, bar over midfoot",
        ],
        "cue": "Brace, sit between your heels, drive the floor away.",
        "notes": "",
    },
    {
        "name": "Front Squat",
        "aliases": [
            "front squats",
            "barbell front squat",
            "barbell front squats",
            "bb front squat",
            "clean grip front squat",
            "front rack squat",
        ],
        "category": "lower_body",
        "camera": "side view, camera at hip height, athlete facing left",
        "equipment": "a barbell loaded with round plates resting on the front of the shoulders in a clean grip, elbows high and pointing forward, fingertips under the bar",
        "setting": "inside a squat rack on a plain gym floor",
        "loop": "pingpong",
        "keyframes": [
            "standing fully upright with the barbell racked on the front of the shoulders, elbows high, feet shoulder-width apart, knees locked, torso vertical",
            "hips starting to drop straight down, knees bent about 20 degrees and pushing forward, torso still vertical, elbows high, bar over midfoot",
            "halfway down, knees bent about 60 degrees, thighs at 45 degrees to the floor, torso nearly vertical, elbows still pointing forward",
            "thighs parallel to the floor, knees well forward over the toes, torso upright, heels flat, elbows high keeping the bar on the shoulders",
            "just below parallel, hips slightly lower than the knees, knees bent about 110 degrees, chest tall, bar still over midfoot",
            "bottom position: deep squat with hips low between the heels, knees fully bent and forward, torso upright, elbows high, heels flat",
        ],
        "cue": "Elbows up, chest tall, sit straight down.",
        "notes": "",
    },
    {
        "name": "Goblet Squat",
        "aliases": [
            "goblet squats",
            "goblet",
            "kettlebell goblet squat",
            "kettlebell goblet squats",
            "kb goblet squat",
            "dumbbell goblet squat",
            "dumbbell goblet squats",
            "db goblet squat",
        ],
        "category": "lower_body",
        "camera": "side view, camera at hip height, athlete facing left",
        "equipment": "a single kettlebell held upside down by the horns against the chest with both hands, elbows tucked under it",
        "setting": "a plain gym floor",
        "loop": "pingpong",
        "keyframes": [
            "standing tall with the kettlebell held against the chest, feet slightly wider than shoulder-width, toes turned out a little, knees locked",
            "hips beginning to sink back and down, knees bent about 20 degrees, torso vertical, kettlebell still tight to the chest",
            "halfway down, knees bent about 60 degrees and pushing out over the toes, thighs at 45 degrees, torso upright, elbows tucked",
            "thighs parallel to the floor, knees out over the toes, torso upright, heels flat, kettlebell held at the sternum",
            "just below parallel, hips lower than the knees, elbows approaching the insides of the knees, chest tall, heels flat",
            "bottom position: deep squat with hips close to the heels, elbows resting inside the knees, torso upright, kettlebell at the chest, heels flat",
        ],
        "cue": "Elbows inside the knees, chest proud.",
        "notes": "",
    },
    {
        "name": "Bulgarian Split Squat",
        "aliases": [
            "bulgarian split squats",
            "bss",
            "rear foot elevated split squat",
            "rear foot elevated split squats",
            "rfess",
            "rfe split squat",
            "bulgarian squat",
            "bulgarian squats",
            "bulgarian lunge",
            "bulgarian lunges",
            "dumbbell bulgarian split squat",
            "dumbbell bulgarian split squats",
            "db bulgarian split squat",
            "bulgarian split squat with dumbbells",
        ],
        "category": "lower_body",
        "camera": "side view, camera at hip height, athlete facing left",
        "equipment": "a dumbbell held in each hand hanging at arm's length at the sides",
        "setting": "a flat bench behind the athlete on a plain gym floor",
        "loop": "pingpong",
        "keyframes": [
            "standing tall on the left leg with the top of the right foot resting on the bench behind, left foot a long stride ahead, front knee straight, dumbbells at the sides",
            "front knee bending about 20 degrees, hips lowering straight down, rear knee drifting toward the floor, torso upright, dumbbells at the sides",
            "front knee bent about 60 degrees, rear knee halfway to the floor, torso leaning slightly forward, dumbbells hanging beside the front leg",
            "front thigh about 30 degrees above parallel, rear knee a foot above the floor, front shin near vertical, torso leaning slightly forward",
            "front thigh nearly parallel to the floor, rear knee a hand's width above the floor, torso leaning slightly forward, dumbbells hanging low",
            "bottom position: front thigh parallel to the floor, front shin vertical, rear knee just above the floor, torso leaning slightly forward, dumbbells beside the front foot",
        ],
        "cue": "Front heel down, drop the back knee straight down.",
        "notes": "",
    },
    {
        "name": "Walking Lunge",
        "aliases": [
            "lunge",
            "lunges",
            "walking lunges",
            "dumbbell walking lunge",
            "dumbbell walking lunges",
            "db walking lunge",
            "db walking lunges",
            "walking lunge with dumbbells",
            "forward lunge",
            "forward lunges",
            "alternating lunge",
            "alternating lunges",
            "alternating forward lunge",
            "alternating forward lunges",
            "dumbbell lunge",
            "dumbbell lunges",
            "db lunges",
            "bodyweight lunge",
            "bodyweight lunges",
        ],
        "category": "lower_body",
        "camera": "side view, camera at hip height, athlete facing left",
        "equipment": "a dumbbell held in each hand hanging at arm's length at the sides",
        "setting": "a plain gym floor with open space ahead of the athlete",
        "loop": "cycle",
        "keyframes": [
            "standing tall with both feet together, dumbbells hanging at the sides, knees straight, torso upright, eyes forward",
            "left foot taking a long stride forward and landing heel first, right heel lifting off the floor behind, torso upright, dumbbells at the sides",
            "bottom of the lunge: left knee bent 90 degrees with the shin vertical, right knee bent 90 degrees just above the floor, torso upright",
            "rising: left leg straightening, right foot pushing off its toes, hips moving forward over the front foot, torso upright, dumbbells steady",
            "standing on the left leg with the right knee swinging forward past the left leg, right foot off the floor, torso upright",
            "right foot landing beside the left foot, both knees slightly bent, weight settling onto both feet, dumbbells hanging at the sides",
        ],
        "cue": "Long stride, tall chest, back knee straight down.",
        "notes": "",
    },
    {
        "name": "Reverse Lunge",
        "aliases": [
            "reverse lunges",
            "backward lunge",
            "backward lunges",
            "step back lunge",
            "step back lunges",
            "rear lunge",
            "rear lunges",
            "dumbbell reverse lunge",
            "dumbbell reverse lunges",
            "db reverse lunge",
            "db reverse lunges",
            "reverse lunge with dumbbells",
            "alternating reverse lunge",
            "alternating reverse lunges",
        ],
        "category": "lower_body",
        "camera": "side view, camera at hip height, athlete facing left",
        "equipment": "a dumbbell held in each hand hanging at arm's length at the sides",
        "setting": "a plain gym floor",
        "loop": "pingpong",
        "keyframes": [
            "standing tall with both feet together, dumbbells hanging at the sides, knees straight, torso upright, eyes forward",
            "right foot lifting and reaching backward, standing on the left leg, torso upright, dumbbells steady at the sides",
            "right toes touching the floor a long stride behind, right heel up, both knees beginning to bend, torso upright",
            "both knees bent about 45 degrees, right knee halfway to the floor, left shin vertical, torso upright, dumbbells at the sides",
            "left thigh nearly parallel to the floor, right knee a hand's width above the floor, torso leaning slightly forward, dumbbells hanging low",
            "bottom position: left thigh parallel to the floor with the shin vertical, right knee just above the floor, torso upright, dumbbells beside the front leg",
        ],
        "cue": "Step back, drop the knee, drive through the front heel.",
        "notes": "",
    },
    {
        "name": "Conventional Deadlift",
        "aliases": [
            "deadlift",
            "deadlifts",
            "dl",
            "barbell deadlift",
            "barbell deadlifts",
            "conventional deadlifts",
            "conventional dl",
            "conv deadlift",
            "regular deadlift",
            "standard deadlift",
        ],
        "category": "lower_body",
        "camera": "side view, camera at hip height, athlete facing left",
        "equipment": "a barbell loaded with large round plates, gripped just outside the legs with an overhand grip, arms straight",
        "setting": "a rubber lifting platform on a plain gym floor",
        "loop": "pingpong",
        "keyframes": [
            "setup: bar on the floor over midfoot, feet hip-width apart, shins touching the bar, hips higher than the knees, back flat, arms straight, shoulders just in front of the bar",
            "plates just leaving the floor, bar at the lower shin, knees and hips extending together, back flat, arms straight, shoulders over the bar",
            "bar at knee height, knees nearly straight, torso at 45 degrees to the floor, back flat, shoulders over the bar, arms straight",
            "bar at mid-thigh, hips driving forward, torso about 25 degrees from vertical, knees nearly straight, arms straight",
            "almost locked out, bar at the upper thigh, torso nearly vertical, hips still slightly bent, arms straight, shoulders back",
            "lockout: standing tall with hips and knees straight, shoulders back, bar hanging at arm's length against the front of the thighs",
        ],
        "cue": "Push the floor away, keep the bar on the shins.",
        "notes": "",
    },
    {
        "name": "Sumo Deadlift",
        "aliases": [
            "sumo deadlifts",
            "sumo dl",
            "sumo barbell deadlift",
            "barbell sumo deadlift",
            "sumo stance deadlift",
            "wide stance deadlift",
        ],
        "category": "lower_body",
        "camera": "three-quarter front view, camera at hip height, athlete facing the camera",
        "equipment": "a barbell loaded with large round plates, gripped with both hands between the knees, arms straight and vertical",
        "setting": "a rubber lifting platform on a plain gym floor",
        "loop": "pingpong",
        "keyframes": [
            "setup: bar on the floor over midfoot, feet very wide with toes turned out, knees pushed out over the toes, hips low, torso upright, arms straight inside the knees",
            "plates just leaving the floor, bar at the lower shin, knees driving outward, hips and shoulders rising together, torso upright, back flat",
            "bar at knee height, knees partly straightened, hips rising, torso about 30 degrees from vertical, arms straight, wide stance unchanged",
            "bar at mid-thigh, hips driving forward, knees nearly straight, torso almost vertical, arms straight between the legs",
            "almost locked out, bar at the upper thigh, hips slightly bent, chest up, shoulders back, feet still very wide",
            "lockout: standing tall in a wide stance with hips and knees straight, shoulders back, bar hanging at arm's length against the thighs",
        ],
        "cue": "Knees out, hips through, chest tall.",
        "notes": "",
    },
    {
        "name": "Romanian Deadlift",
        "aliases": [
            "rdl",
            "rdls",
            "romanian deadlifts",
            "romanian dl",
            "barbell romanian deadlift",
            "barbell romanian deadlifts",
            "barbell rdl",
            "bb rdl",
            "dumbbell romanian deadlift",
            "dumbbell romanian deadlifts",
            "dumbbell rdl",
            "db rdl",
            "stiff leg deadlift",
            "stiff leg deadlifts",
            "stiff legged deadlift",
            "stiff legged deadlifts",
        ],
        "category": "lower_body",
        "camera": "side view, camera at hip height, athlete facing left",
        "equipment": "a barbell loaded with round plates held at arm's length in front of the thighs, overhand grip",
        "setting": "a plain gym floor",
        "loop": "pingpong",
        "keyframes": [
            "standing tall with the bar at arm's length against the front of the thighs, feet hip-width apart, knees soft, shoulders back",
            "hips pushing back, torso tilting about 20 degrees forward, bar sliding down to just above the knees, knees slightly bent, arms straight",
            "torso about 40 degrees forward, hips further back, bar at the kneecaps, shins vertical, back flat, arms straight",
            "torso about 55 degrees forward, bar just below the knees against the shins, knees slightly bent, back flat, shoulders back",
            "torso about 70 degrees forward, bar at the upper shin, hips pushed far back, hamstrings stretched, arms straight, back flat",
            "bottom position: torso nearly parallel to the floor, bar at mid-shin close to the legs, knees slightly bent, back flat, shins vertical",
        ],
        "cue": "Hips back, bar on the legs, soft knees.",
        "notes": "",
    },
    {
        "name": "Trap Bar Deadlift",
        "aliases": [
            "trap bar deadlifts",
            "trap bar dl",
            "trap bar",
            "trapbar deadlift",
            "hex bar deadlift",
            "hex bar deadlifts",
            "hex bar dl",
            "hex bar",
            "hexbar deadlift",
            "tbdl",
        ],
        "category": "lower_body",
        "camera": "side view, camera at hip height, athlete facing left",
        "equipment": "a hexagonal trap bar loaded with round plates, the athlete standing inside the frame gripping the neutral handles at the sides",
        "setting": "a rubber lifting platform on a plain gym floor",
        "loop": "pingpong",
        "keyframes": [
            "setup: standing inside the trap bar with the plates on the floor, feet hip-width apart, hips above the knees, back flat, arms straight gripping the side handles",
            "plates just leaving the floor, handles at shin height, knees and hips extending together, torso about 45 degrees from vertical, arms straight",
            "handles at knee height, knees partly straightened, torso about 35 degrees from vertical, back flat, arms straight at the sides",
            "handles at mid-thigh, hips driving forward, knees nearly straight, torso about 20 degrees from vertical, arms straight",
            "almost locked out, handles at the upper thigh, torso nearly vertical, hips slightly bent, shoulders back, arms straight",
            "lockout: standing tall inside the frame with hips and knees straight, shoulders back, arms straight holding the handles at the sides",
        ],
        "cue": "Stand up through the middle of the bar.",
        "notes": "Draw the hexagonal frame of the bar around the athlete's legs, with the plates outside the frame and the handles at hip width.",
    },
    {
        "name": "Hip Thrust",
        "aliases": [
            "hip thrusts",
            "barbell hip thrust",
            "barbell hip thrusts",
            "bb hip thrust",
            "dumbbell hip thrust",
            "dumbbell hip thrusts",
            "db hip thrust",
            "weighted hip thrust",
        ],
        "category": "lower_body",
        "camera": "side view, camera at hip height, athlete facing left with the bench on the right",
        "equipment": "a barbell loaded with round plates resting across the crease of the hips on a thick foam pad, hands holding the bar either side of the hips",
        "setting": "a flat bench on a plain gym floor, the athlete's upper back resting on the edge of the bench",
        "loop": "pingpong",
        "keyframes": [
            "bottom position: upper back on the bench edge, hips near the floor, knees bent, feet flat about shoulder-width apart, bar across the hips, chin tucked",
            "hips lifting a hand's width off the floor, knees bent about 100 degrees, shins angled forward, bar rising with the hips, feet flat",
            "hips halfway up, torso angled up from the bench, knees bent about 95 degrees, feet flat, bar steady over the hips",
            "hips most of the way up, torso nearly level, shins close to vertical, bar held steady at the hips, chin tucked",
            "just short of lockout, hips a little below shoulder height, knees bent 90 degrees, ribs down, feet flat, bar over the hips",
            "top position: hips fully extended so torso and thighs form a straight line from shoulders to knees, shins vertical, chin tucked, bar over the hips",
        ],
        "cue": "Drive through the heels, squeeze the glutes at the top.",
        "notes": "",
    },
    {
        "name": "Glute Bridge",
        "aliases": [
            "glute bridges",
            "hip bridge",
            "hip bridges",
            "floor bridge",
            "floor bridges",
            "supine bridge",
            "bodyweight glute bridge",
            "bodyweight glute bridges",
            "barbell glute bridge",
        ],
        "category": "lower_body",
        "camera": "side view, camera low near floor level, athlete facing left with the head on the right",
        "equipment": "no equipment",
        "setting": "an exercise mat on a plain gym floor",
        "loop": "pingpong",
        "keyframes": [
            "lying flat on the back with knees bent about 90 degrees, feet flat hip-width apart, arms flat on the mat at the sides, hips resting on the mat",
            "hips lifting just off the mat, lower back still close to the floor, feet flat, arms pressing into the mat, chin tucked",
            "hips a hand's width off the mat, torso beginning to angle up from the shoulders, knees bent, feet flat, arms flat",
            "hips halfway up, thighs and torso forming a shallow angle, shoulders and upper back on the mat, arms flat at the sides",
            "hips nearly at full height, shins vertical, weight on the upper back and heels, ribs down, arms flat on the mat",
            "top position: hips fully extended so shoulders, hips and knees form a straight line, shins vertical, feet flat, arms flat on the mat",
        ],
        "cue": "Heels down, squeeze the glutes, ribs tucked.",
        "notes": "",
    },
    {
        "name": "Leg Press",
        "aliases": [
            "leg presses",
            "45 degree leg press",
            "machine leg press",
            "leg press machine",
            "sled leg press",
            "plate loaded leg press",
            "incline leg press",
        ],
        "category": "lower_body",
        "camera": "side view, camera at hip height, athlete facing left with the footplate on the left",
        "equipment": "a 45-degree leg press machine with round plates loaded on the sled, hands gripping the side handles of the seat",
        "setting": "a plain gym floor, the athlete reclined in the seat of the machine",
        "loop": "pingpong",
        "keyframes": [
            "reclined in the seat with the back flat against the backrest, feet flat and hip-width on the footplate, legs extended with knees soft, hands on the side handles",
            "sled lowering, knees bent about 25 degrees, feet flat on the plate, hips pressed into the seat, hands on the handles",
            "knees bent about 50 degrees, sled a quarter of the way down the rails, feet flat, lower back flat on the pad",
            "knees bent about 75 degrees, thighs approaching the chest, feet flat on the plate, back flat against the pad",
            "knees bent about 100 degrees, thighs close to the chest, lower back still flat on the pad, hands on the handles",
            "bottom position: knees bent about 115 degrees with thighs near the chest, feet flat on the plate, lower back flat on the backrest, hands on the handles",
        ],
        "cue": "Feet flat, lower slow, never lock the knees.",
        "notes": "",
    },
    {
        "name": "Step-up",
        "aliases": [
            "step ups",
            "stepup",
            "stepups",
            "box step up",
            "box step ups",
            "step up onto box",
            "dumbbell step up",
            "dumbbell step ups",
            "db step up",
            "db step ups",
            "weighted step up",
            "weighted step ups",
            "step up with dumbbells",
        ],
        "category": "lower_body",
        "camera": "side view, camera at hip height, athlete facing left",
        "equipment": "a dumbbell held in each hand hanging at arm's length at the sides",
        "setting": "a knee-high plyo box on a plain gym floor directly in front of the athlete",
        "loop": "pingpong",
        "keyframes": [
            "standing on the floor facing the box, left foot flat on top of the box with the knee bent 90 degrees, right foot on the floor, dumbbells at the sides",
            "leaning slightly forward over the left foot, right heel lifting off the floor, left leg beginning to straighten, dumbbells at the sides",
            "left leg halfway extended, right foot off the floor trailing behind, torso upright, dumbbells hanging steady at the sides",
            "left leg nearly straight, right foot rising level with the top of the box, torso upright, dumbbells at the sides",
            "standing on the left leg on top of the box, right foot passing beside the left knee, torso upright, dumbbells at the sides",
            "top position: standing tall on top of the box on the left leg, right knee lifted to hip height with the foot hanging, torso upright, dumbbells at the sides",
        ],
        "cue": "Drive through the whole foot on the box.",
        "notes": "",
    },
    {
        "name": "Standing Calf Raise",
        "aliases": [
            "calf raise",
            "calf raises",
            "calves",
            "standing calf raises",
            "dumbbell calf raise",
            "dumbbell calf raises",
            "db calf raise",
            "db calf raises",
            "standing dumbbell calf raise",
            "barbell calf raise",
            "barbell calf raises",
            "standing barbell calf raise",
            "machine calf raise",
            "machine calf raises",
            "standing machine calf raise",
            "smith machine calf raise",
            "calf raise on step",
            "heel raise",
            "heel raises",
        ],
        "category": "lower_body",
        "camera": "side view, camera at hip height, athlete facing left",
        "equipment": "a dumbbell held in each hand hanging at arm's length at the sides",
        "setting": "a low step block on a plain gym floor, the balls of the feet on the edge of the step with the heels hanging off",
        "loop": "pingpong",
        "keyframes": [
            "standing tall with the balls of the feet on the edge of the step, heels dropped well below the step, knees straight, dumbbells at the sides",
            "heels rising level with the top of the step, ankles neutral, knees straight, torso upright, dumbbells at the sides",
            "heels a little above the step, weight moving onto the balls of the feet, knees straight, torso tall",
            "heels raised about halfway to full height, ankles extending, knees straight, body tall, dumbbells at the sides",
            "heels raised high, most of the way up, calves contracted, knees straight, torso tall, dumbbells at the sides",
            "top position: standing fully up on the balls of the feet with the heels as high as possible, ankles fully extended, knees straight, dumbbells at the sides",
        ],
        "cue": "Full stretch at the bottom, pause at the top.",
        "notes": "",
    },
    {
        "name": "Box Jump",
        "aliases": [
            "box jumps",
            "plyo box jump",
            "plyo box jumps",
            "jump to box",
            "jumps to box",
            "box jumping",
        ],
        "category": "lower_body",
        "camera": "side view, camera at hip height, athlete facing left",
        "equipment": "no equipment",
        "setting": "a knee-high plyo box on a plain gym floor a short step in front of the athlete",
        "loop": "cycle",
        "keyframes": [
            "standing tall on the floor a short step in front of the box, feet hip-width apart, knees soft, arms hanging at the sides",
            "countermovement: quarter squat with hips pushed back, torso leaning forward, arms swung straight back behind the hips",
            "take-off: hips, knees and ankles fully extended, toes just leaving the floor, arms swung forward and up overhead",
            "peak of the jump: body in the air above box height with knees and hips tucked, feet pulled up under the hips, arms out in front",
            "landing: both feet flat on top of the box, knees and hips bent in a quarter squat, torso leaning slightly forward, arms out in front for balance",
            "standing tall on top of the box with one foot stepping backward off the edge toward the floor, arms hanging at the sides",
        ],
        "cue": "Swing the arms, land soft, stand tall.",
        "notes": "",
    },
    {
        "name": "Kettlebell Swing",
        "aliases": [
            "swing",
            "swings",
            "kettlebell swings",
            "kettle bell swing",
            "kb swing",
            "kb swings",
            "kbs",
            "russian kettlebell swing",
            "russian kettlebell swings",
            "russian swing",
            "russian swings",
            "two hand kettlebell swing",
            "two handed kettlebell swing",
            "two hand swing",
            "two handed swing",
            "hardstyle swing",
            "hardstyle kettlebell swing",
        ],
        "category": "lower_body",
        "camera": "side view, camera at hip height, athlete facing left",
        "equipment": "a single kettlebell held by the handle with both hands, arms straight",
        "setting": "a plain gym floor",
        "loop": "pingpong",
        "keyframes": [
            "bottom of the swing: hips hinged back with the torso about 45 degrees from the floor, knees slightly bent, arms straight, kettlebell swung back behind the knees, forearms against the inner thighs",
            "hips beginning to drive forward, torso rising to about 60 degrees, arms straight, kettlebell passing forward between the knees",
            "torso nearly upright, hips almost extended, arms straight and angled down, kettlebell at knee height in front of the legs",
            "standing fully upright with glutes squeezed, arms straight, kettlebell floating at hip height in front of the body",
            "standing tall, arms straight and rising to about 45 degrees below horizontal, kettlebell at belly height in front",
            "top of the swing: standing tall, arms straight and parallel to the floor, kettlebell at shoulder height with the handle horizontal",
        ],
        "cue": "Hinge, snap the hips, let the bell float.",
        "notes": "",
    },
    {
        "name": "Good Morning",
        "aliases": [
            "good mornings",
            "barbell good morning",
            "barbell good mornings",
            "bb good morning",
            "bb good mornings",
        ],
        "category": "lower_body",
        "camera": "side view, camera at hip height, athlete facing left",
        "equipment": "a barbell loaded with round plates resting across the upper back, hands gripping the bar just outside the shoulders",
        "setting": "inside a squat rack on a plain gym floor",
        "loop": "pingpong",
        "keyframes": [
            "standing tall with the bar across the upper back, feet hip-width apart, knees soft, torso vertical, chest up",
            "hips pushing back, torso tilting about 20 degrees forward, knees slightly bent, bar over midfoot, back flat",
            "torso about 40 degrees forward, hips further back, shins vertical, back flat, bar still across the upper back",
            "torso about 55 degrees forward, hips pushed well back, knees slightly bent, chest up, back flat",
            "torso about 70 degrees forward, hamstrings stretched, back flat, knees slightly bent, bar staying over midfoot",
            "bottom position: torso nearly parallel to the floor, hips pushed far back, knees slightly bent, back flat, bar across the upper back",
        ],
        "cue": "Hips back, chest up, feel the hamstrings.",
        "notes": "",
    },
    {
        "name": "Nordic Hamstring Curl",
        "aliases": [
            "nordic curl",
            "nordic curls",
            "nordics",
            "nordic",
            "nordic hamstring curls",
            "nordic ham curl",
            "nordic ham curls",
            "nordic hamstring",
            "nordic leg curl",
            "nordic leg curls",
            "natural glute ham raise",
            "natural ghr",
            "russian lean",
            "russian leans",
            "harop curl",
        ],
        "category": "lower_body",
        "camera": "side view, camera at hip height, athlete facing left",
        "equipment": "no held load; the ankles are hooked under a padded anchor bar behind the athlete",
        "setting": "a thick exercise mat on a plain gym floor with a padded ankle anchor at the rear",
        "loop": "pingpong",
        "keyframes": [
            "kneeling upright on the mat with the ankles held under the anchor pad, hips fully extended, torso vertical, arms bent at the sides with palms facing forward",
            "torso leaning about 15 degrees forward from the knees, hips still extended, straight line from knees to head, hands ready in front",
            "torso about 30 degrees forward, straight line from knees to head, hands held in front of the chest, ankles under the pad",
            "torso about 45 degrees forward, straight line from knees to head, hands reaching down toward the floor",
            "torso about 60 degrees forward, hands just above the mat, body straight from the knees to the head, ankles under the pad",
            "bottom position: body nearly parallel to the floor in a straight line from knees to shoulders, palms touching the mat, elbows bent",
        ],
        "cue": "Hips open, lower slow, catch with the hands.",
        "notes": "",
    },
    {
        "name": "Lying Leg Curl",
        "aliases": [
            "leg curl",
            "leg curls",
            "lying leg curls",
            "prone leg curl",
            "prone leg curls",
            "hamstring curl",
            "hamstring curls",
            "ham curl",
            "ham curls",
            "machine leg curl",
            "machine leg curls",
            "machine hamstring curl",
            "lying hamstring curl",
            "lying hamstring curls",
            "prone hamstring curl",
        ],
        "category": "lower_body",
        "camera": "side view, camera at hip height, athlete facing left, lying face down with the head on the left",
        "equipment": "a lying leg curl machine with a weight stack, padded roller resting on the back of the ankles, hands gripping the handles under the bench",
        "setting": "a plain gym floor, the athlete lying face down on the machine's angled bench",
        "loop": "pingpong",
        "keyframes": [
            "lying face down on the bench with hips flat on the pad, legs straight, ankle roller resting on the back of the ankles, hands on the handles",
            "knees bending about 25 degrees, heels lifting the roller, hips staying flat on the pad, hands on the handles",
            "knees bent about 50 degrees, shins at 45 degrees to the bench, hips flat on the pad, torso still",
            "knees bent about 75 degrees, shins near vertical, hips pressed into the pad, chest on the bench",
            "knees bent about 100 degrees, roller moving toward the glutes, hips flat, torso still on the bench",
            "top position: knees fully bent with heels close to the glutes, roller at the top of its arc, hips flat on the pad, torso still",
        ],
        "cue": "Hips down, curl the heels to the glutes.",
        "notes": "",
    },
    {
        "name": "Leg Extension",
        "aliases": [
            "leg extensions",
            "machine leg extension",
            "machine leg extensions",
            "seated leg extension",
            "seated leg extensions",
            "leg extension machine",
            "quad extension",
            "quad extensions",
            "knee extension",
            "knee extensions",
        ],
        "category": "lower_body",
        "camera": "side view, camera at hip height, athlete facing left",
        "equipment": "a seated leg extension machine with a weight stack, padded roller across the front of the ankles, hands gripping the side handles",
        "setting": "a plain gym floor, the athlete seated upright in the machine",
        "loop": "pingpong",
        "keyframes": [
            "seated with the back against the pad, knees bent 90 degrees, shins vertical, roller across the front of the ankles, hands on the side handles",
            "knees extending about 20 degrees, shins swinging forward, back on the pad, hands on the handles",
            "knees bent about 50 degrees, shins at 45 degrees to the floor, thighs flat on the seat, back on the pad",
            "knees bent about 30 degrees, lower legs rising, thighs still flat on the seat, torso upright",
            "knees nearly straight, lower legs almost in line with the thighs, toes pointing up, back against the pad",
            "top position: knees fully extended so the legs are straight and parallel to the floor, toes pointing up, back against the pad",
        ],
        "cue": "Straighten fully, lower under control.",
        "notes": "",
    },
    {
        "name": "Hack Squat",
        "aliases": [
            "hack squats",
            "machine hack squat",
            "machine hack squats",
            "hack squat machine",
            "sled hack squat",
        ],
        "category": "lower_body",
        "camera": "side view, camera at hip height, athlete facing left",
        "equipment": "a hack squat machine with round plates loaded on the sled, shoulders under the shoulder pads, hands on the side handles",
        "setting": "a plain gym floor, the athlete standing on the angled footplate with the back against the backrest",
        "loop": "pingpong",
        "keyframes": [
            "standing tall on the footplate with the back against the pad, shoulders under the pads, feet shoulder-width apart, knees soft, hands on the handles",
            "knees bending about 25 degrees, sled sliding down the rails, back flat against the pad, heels flat on the plate",
            "knees bent about 50 degrees, thighs at 45 degrees to the footplate, back against the pad, heels flat",
            "knees bent about 75 degrees, thighs approaching parallel to the footplate, heels flat, shoulders under the pads",
            "knees bent about 100 degrees, thighs parallel to the footplate, hips low, back still flat against the pad",
            "bottom position: knees bent about 120 degrees with hips low near the footplate, heels flat, back and shoulders still against the pads",
        ],
        "cue": "Back on the pad, knees over toes, sit deep.",
        "notes": "",
    },
    {
        "name": "Single-leg Romanian Deadlift",
        "aliases": [
            "single leg rdl",
            "single leg rdls",
            "sl rdl",
            "slrdl",
            "single leg romanian deadlifts",
            "single leg deadlift",
            "single leg deadlifts",
            "single leg dl",
            "sl deadlift",
            "one leg rdl",
            "one leg romanian deadlift",
            "one leg deadlift",
            "one legged deadlift",
            "one legged rdl",
            "dumbbell single leg rdl",
            "db single leg rdl",
            "kettlebell single leg rdl",
            "kb single leg rdl",
            "single leg kettlebell deadlift",
            "single leg dumbbell deadlift",
        ],
        "category": "lower_body",
        "camera": "side view, camera at hip height, athlete facing left",
        "equipment": "a single kettlebell held in the right hand hanging at arm's length in front of the thigh",
        "setting": "a plain gym floor",
        "loop": "pingpong",
        "keyframes": [
            "standing tall on the left leg with the right foot lifted just off the floor, kettlebell hanging in the right hand in front of the thigh, left arm at the side",
            "hips hinging back, torso tilting about 20 degrees forward, right leg extending straight behind, standing knee soft, kettlebell at the thigh",
            "torso about 40 degrees forward, right leg lifted behind in line with the torso, kettlebell at the knee of the standing leg, hips square",
            "torso about 55 degrees forward, rear leg raised higher, hips square, kettlebell at the shin, left arm out for balance",
            "torso about 70 degrees forward, rear leg nearly in line with the torso, kettlebell at mid-shin, left arm reaching out for balance",
            "bottom position: torso and rear leg forming one straight line parallel to the floor, standing knee slightly bent, kettlebell hanging at mid-shin, hips square",
        ],
        "cue": "Reach the back foot to the wall behind you.",
        "notes": "",
    },
]
