"""Upper-body pulling movements: vertical pulls, rows, rear delts, biceps, traps and hangs.

Camera conventions used here: vertical pulls (pull-up, chin-up, lat pulldown) are shown from
the front so the grip width and the body rising past the bar are obvious; rows, curls and the
straight-arm pulldown are shown from the side (athlete facing left) so the elbow path and the
torso angle read clearly; rear-delt work and the band pull-apart use a three-quarter front
view so both arms sweeping outward are visible.
"""

EXERCISES = [
    {
        "name": "Pull-up",
        "aliases": [
            "pullup",
            "pullups",
            "pull ups",
            "strict pull up",
            "strict pullup",
            "strict pull ups",
            "bodyweight pull up",
            "bodyweight pullup",
            "bodyweight pull ups",
            "wide grip pull up",
            "wide grip pullup",
            "wide grip pull ups",
            "overhand pull up",
            "overhand pullup",
            "pronated pull up",
            "pronated pullup",
            "weighted pull up",
            "weighted pullup",
            "weighted pull ups",
            "assisted pull up",
            "assisted pullup",
            "assisted pull ups",
            "banded pull up",
            "banded pullup",
            "band assisted pull up",
            "band assisted pullup",
            "neutral grip pull up",
            "neutral grip pullup",
            "neutral grip pull ups",
            "dead hang pull up",
            "dead hang pull ups",
            "chest to bar pull up",
            "chest to bar pull ups",
            "chest to bar",
        ],
        "category": "upper_pull",
        "camera": "front view, camera at chest height, athlete facing the camera",
        "equipment": "a fixed horizontal pull-up bar overhead, gripped with an overhand grip slightly wider than the shoulders, palms facing away",
        "setting": "a high pull-up bar on a plain gym floor, the feet hanging clear of the floor",
        "loop": "pingpong",
        "keyframes": [
            "dead hang: arms fully straight overhead gripping the bar wider than the shoulders, shoulders relaxed up by the ears, body straight, legs together with toes pointing down",
            "shoulder blades pulling down and back so the body rises a hand's width, elbows still nearly straight, chest lifting slightly, legs straight and still",
            "elbows bent about 45 degrees and pointing down and out, upper arms angled away from the torso, head a forearm's length below the bar, legs straight",
            "elbows bent 90 degrees with upper arms parallel to the floor, chest rising toward the bar, eyes level with the bar, torso slightly arched, legs straight",
            "elbows bent past 90 degrees and driving down toward the ribs, chin level with the bar, chest up and open, legs straight and together",
            "top position: chin clearly above the bar, elbows fully bent and pulled down beside the ribs, chest close to the bar, shoulders down, legs straight together",
        ],
        "cue": "Pull the elbows to your pockets, chin over bar.",
        "notes": "",
    },
    {
        "name": "Chin-up",
        "aliases": [
            "chinup",
            "chinups",
            "chin ups",
            "chin",
            "chins",
            "underhand pull up",
            "underhand pullup",
            "underhand pull ups",
            "supinated pull up",
            "supinated pullup",
            "supinated pull ups",
            "reverse grip pull up",
            "reverse grip pullup",
            "reverse grip pull ups",
            "weighted chin up",
            "weighted chinup",
            "weighted chin ups",
            "bodyweight chin up",
            "bodyweight chinup",
            "strict chin up",
            "strict chinup",
            "assisted chin up",
            "assisted chinup",
            "banded chin up",
            "banded chinup",
            "band assisted chin up",
        ],
        "category": "upper_pull",
        "camera": "front view, camera at chest height, athlete facing the camera",
        "equipment": "a fixed horizontal pull-up bar overhead, gripped with an underhand grip at shoulder width, palms facing the athlete",
        "setting": "a high pull-up bar on a plain gym floor, the feet hanging clear of the floor",
        "loop": "pingpong",
        "keyframes": [
            "dead hang: arms fully straight overhead with palms facing the athlete at shoulder width, shoulders relaxed up by the ears, body straight, toes pointing down",
            "shoulder blades pulling down so the body rises a hand's width, elbows just beginning to bend, forearms vertical, legs straight and together",
            "elbows bent about 45 degrees and pointing straight down in front of the ribs, forearms vertical, head a forearm's length below the bar, legs straight",
            "elbows bent 90 degrees and tucked in front of the torso, eyes level with the bar, chest lifting, torso slightly arched, legs straight together",
            "elbows bent past 90 degrees close to the ribs, chin level with the bar, upper arms nearly vertical against the sides, legs straight",
            "top position: chin clearly above the bar, elbows fully bent and pointing down beside the ribs, chest close to the bar, shoulders down, legs straight together",
        ],
        "cue": "Elbows down and in, chin over the bar.",
        "notes": "",
    },
    {
        "name": "Lat Pulldown",
        "aliases": [
            "lat pulldowns",
            "lat pull down",
            "lat pull downs",
            "pulldown",
            "pulldowns",
            "pull downs",
            "cable pulldown",
            "cable pulldowns",
            "cable lat pulldown",
            "cable lat pulldowns",
            "wide grip lat pulldown",
            "wide grip lat pulldowns",
            "wide grip pulldown",
            "wide grip pulldowns",
            "wide grip pull down",
            "close grip lat pulldown",
            "close grip pulldown",
            "close grip pull down",
            "neutral grip lat pulldown",
            "neutral grip pulldown",
            "neutral grip pull down",
            "underhand lat pulldown",
            "underhand pulldown",
            "reverse grip lat pulldown",
            "reverse grip pulldown",
            "supinated lat pulldown",
            "machine lat pulldown",
            "lat pulldown machine",
            "pulldown machine",
            "seated lat pulldown",
            "front lat pulldown",
            "lat pulldown wide grip",
            "lats pulldown",
            "lat machine",
        ],
        "category": "upper_pull",
        "camera": "three-quarter front view, camera at chest height, athlete facing the camera",
        "equipment": "a long straight lat pulldown bar hanging from a high cable, gripped overhand wider than the shoulders, palms facing away",
        "setting": "seated on the bench of a lat pulldown station with the thighs tucked under the knee pads, feet flat on the floor, weight stack behind",
        "loop": "pingpong",
        "keyframes": [
            "seated upright with the thighs under the knee pads, arms fully extended straight up gripping the wide bar, shoulders relaxed up toward the ears, chest tall",
            "shoulder blades pulling down and back, bar lowering a hand's width, elbows just beginning to bend and flare outward, torso leaning back about 10 degrees",
            "elbows bent about 45 degrees and pointing down and out, bar just above the top of the head, chest lifted, torso leaning back slightly, feet flat",
            "elbows bent 90 degrees with upper arms parallel to the floor, bar level with the eyes in front of the face, chest up, torso leaning back about 15 degrees",
            "elbows driving down past 90 degrees toward the ribs, bar at chin height, chest open and proud, torso steady, thighs held under the pads",
            "bottom position: bar touching the upper chest just below the collarbones, elbows fully bent and pulled down beside the ribs, shoulder blades squeezed, torso leaning back slightly",
        ],
        "cue": "Elbows down to the ribs, bar to the collarbones.",
        "notes": "",
    },
    {
        "name": "Barbell Row",
        "aliases": [
            "barbell rows",
            "bb row",
            "bb rows",
            "bent over row",
            "bent over rows",
            "bent row",
            "bent rows",
            "bent over barbell row",
            "bent over barbell rows",
            "barbell bent over row",
            "barbell bent over rows",
            "bent over bb row",
            "bb bent over row",
            "overhand barbell row",
            "underhand barbell row",
            "underhand bent over row",
            "supinated barbell row",
            "yates row",
            "yates rows",
            "bent over barbell rows overhand",
            "standing barbell row",
        ],
        "category": "upper_pull",
        "camera": "side view, camera at hip height, athlete facing left",
        "equipment": "a barbell loaded with round plates held at arm's length below the shoulders, overhand grip just wider than the shoulders",
        "setting": "a plain gym floor",
        "loop": "pingpong",
        "keyframes": [
            "hinged at the hips with the torso about 45 degrees from the floor, knees slightly bent, back flat, arms straight so the bar hangs below the shoulders at knee height",
            "elbows just beginning to bend and drift back, bar rising a hand's width off the knees, torso and knees held still, back flat",
            "elbows bent about 45 degrees and pointing behind the torso, bar at mid-thigh, forearms vertical, shoulder blades starting to draw together",
            "elbows bent 90 degrees close to the sides, bar a hand's width below the torso, shoulder blades squeezing, torso still at 45 degrees",
            "elbows driving past the torso, bar almost touching the lower ribs, upper arms angled back past the back, chest up, back flat",
            "top position: bar touching the lower ribs just above the navel, elbows fully bent and pointing up behind the back, shoulder blades pinched, torso still at 45 degrees",
        ],
        "cue": "Hinge, brace, pull the bar to your belly.",
        "notes": "",
    },
    {
        "name": "Pendlay Row",
        "aliases": [
            "pendlay rows",
            "pendlay",
            "pendlays",
            "pendlay barbell row",
            "barbell pendlay row",
            "pendlay bb row",
            "dead stop row",
            "dead stop rows",
            "dead stop barbell row",
            "dead stop bent over row",
            "barbell row from the floor",
            "barbell row from floor",
            "floor row",
            "floor rows",
        ],
        "category": "upper_pull",
        "camera": "side view, camera at hip height, athlete facing left",
        "equipment": "a barbell loaded with large round plates resting on the floor, gripped overhand just wider than the shoulders",
        "setting": "a rubber lifting platform on a plain gym floor",
        "loop": "pingpong",
        "keyframes": [
            "setup: plates resting on the floor, torso hinged parallel to the floor with a flat back, knees slightly bent, arms straight and vertical gripping the bar, head neutral",
            "plates just lifting off the floor, elbows beginning to bend, torso still parallel to the floor, knees held still, arms nearly straight",
            "bar at mid-shin, elbows bent about 45 degrees and flaring slightly back, torso still parallel to the floor, shoulder blades drawing together",
            "bar at knee height, elbows bent 90 degrees and pointing up behind the back, forearms vertical, torso flat and horizontal, knees slightly bent",
            "bar a hand's width below the chest, elbows bent past 90 degrees and driving up past the torso, shoulder blades pinched, torso still horizontal",
            "top position: bar touching the lower chest, elbows fully bent and pulled up high behind the back, torso parallel to the floor, back flat, knees slightly bent",
        ],
        "cue": "Back flat, explode the bar to your chest, reset.",
        "notes": "",
    },
    {
        "name": "Dumbbell Row",
        "aliases": [
            "dumbbell rows",
            "db row",
            "db rows",
            "one arm dumbbell row",
            "one arm dumbbell rows",
            "one arm db row",
            "one arm db rows",
            "single arm dumbbell row",
            "single arm dumbbell rows",
            "single arm db row",
            "single arm db rows",
            "1 arm dumbbell row",
            "1 arm db row",
            "sa db row",
            "one arm row",
            "one arm rows",
            "single arm row",
            "single arm rows",
            "bench supported dumbbell row",
            "bench supported row",
            "dumbbell row on bench",
            "one arm bent over row",
            "bent over dumbbell row",
            "bent over dumbbell rows",
            "bent over db row",
            "bent over db rows",
            "dumbbell bent over row",
            "db bent over row",
            "kroc row",
            "kroc rows",
            "three point row",
            "3 point row",
            "3 point dumbbell row",
            "tripod row",
            "tripod dumbbell row",
        ],
        "category": "upper_pull",
        "camera": "side view, camera at hip height, athlete facing left",
        "equipment": "a single dumbbell held in the left hand nearest the camera, hanging at arm's length below the shoulder",
        "setting": "a flat bench on a plain gym floor, the athlete's right hand and right knee braced on the bench with the left foot flat on the floor",
        "loop": "pingpong",
        "keyframes": [
            "right hand and right knee on the bench, left foot flat on the floor, torso parallel to the floor with a flat back, left arm straight so the dumbbell hangs below the shoulder",
            "left elbow just beginning to bend, dumbbell rising a hand's width, shoulder blade drawing toward the spine, torso and hips square and still",
            "left elbow bent about 45 degrees and pointing back, dumbbell level with the knee of the standing leg, forearm vertical, torso flat",
            "left elbow bent 90 degrees close to the ribs, dumbbell a hand's width below the torso, upper arm in line with the torso, back flat",
            "left elbow driving up past the torso, dumbbell almost touching the hip, upper arm angled above the back, torso still parallel to the floor",
            "top position: dumbbell touching the side of the hip, left elbow fully bent and pointing up toward the ceiling behind the back, shoulder blade pinched, torso flat",
        ],
        "cue": "Drive the elbow to the hip, keep the hips square.",
        "notes": "",
    },
    {
        "name": "Seated Cable Row",
        "aliases": [
            "seated cable rows",
            "cable row",
            "cable rows",
            "seated row",
            "seated rows",
            "seated rowing",
            "low row",
            "low rows",
            "low cable row",
            "low cable rows",
            "seated low row",
            "seated low rows",
            "cable seated row",
            "cable seated rows",
            "seated cable row machine",
            "seated row machine",
            "cable row machine",
            "v bar row",
            "v bar rows",
            "v bar cable row",
            "v bar seated row",
            "close grip cable row",
            "close grip seated row",
            "close grip seated cable row",
            "neutral grip cable row",
            "neutral grip seated row",
            "wide grip cable row",
            "wide grip seated row",
            "rope cable row",
            "seated rope row",
            "seated horizontal row",
            "horizontal cable row",
        ],
        "category": "upper_pull",
        "camera": "side view, camera at hip height, athlete facing left toward the cable station on the left edge",
        "equipment": "a V-shaped double handle on a low cable pulley, gripped with both hands palms facing each other, the cable running forward to the weight stack",
        "setting": "seated on the padded bench of a cable row station, feet flat on the angled footplate, knees slightly bent, weight stack at the left edge",
        "loop": "pingpong",
        "keyframes": [
            "seated with the torso upright, knees slightly bent and feet on the footplate, arms fully extended forward toward the pulley with the cable taut, shoulders reaching forward",
            "shoulder blades pulling back, elbows beginning to bend, handle moving a hand's width toward the body, torso upright and still, knees slightly bent",
            "elbows bent about 45 degrees and staying close to the sides, handle level with the knees, chest lifting, torso vertical, feet braced",
            "elbows bent 90 degrees beside the ribs, handle a forearm's length in front of the navel, shoulder blades drawing together, torso upright",
            "elbows driving back past the torso, handle almost at the belly, chest proud, shoulders down and back, torso vertical, knees slightly bent",
            "end position: handle touching the navel, elbows fully bent and pulled behind the torso, shoulder blades squeezed together, torso upright, knees slightly bent",
        ],
        "cue": "Chest tall, pull the handle to your belly button.",
        "notes": "",
    },
    {
        "name": "Chest-supported Row",
        "aliases": [
            "chest supported rows",
            "chest supported dumbbell row",
            "chest supported dumbbell rows",
            "chest supported db row",
            "chest supported db rows",
            "chest supported machine row",
            "chest supported t bar row",
            "chest supported cable row",
            "incline dumbbell row",
            "incline dumbbell rows",
            "incline db row",
            "incline db rows",
            "incline bench row",
            "incline bench rows",
            "incline bench dumbbell row",
            "incline prone row",
            "prone dumbbell row",
            "prone dumbbell rows",
            "prone row",
            "prone rows",
            "prone incline row",
            "seal row",
            "seal rows",
            "bench row",
            "bench rows",
            "machine row",
            "machine rows",
            "seated machine row",
            "hammer strength row",
            "plate loaded row",
            "chest supported incline row",
            "csr",
        ],
        "category": "upper_pull",
        "camera": "side view, camera at hip height, athlete facing left",
        "equipment": "a dumbbell held in each hand hanging at arm's length below the shoulders, palms facing each other",
        "setting": "an incline bench set to about 45 degrees on a plain gym floor, the athlete lying face down with the chest on the pad and the feet on the floor behind",
        "loop": "pingpong",
        "keyframes": [
            "lying face down on the incline bench with the chest on the pad, feet on the floor behind, arms hanging straight down with the dumbbells below the shoulders, head neutral",
            "elbows just beginning to bend and drift back, dumbbells rising a hand's width, shoulder blades drawing toward the spine, chest still on the pad",
            "elbows bent about 45 degrees and pointing back, dumbbells level with the bottom of the bench pad, forearms vertical, chest pressed into the pad",
            "elbows bent 90 degrees close to the ribs, dumbbells a hand's width below the torso, upper arms in line with the torso, chest on the pad",
            "elbows driving up past the torso, dumbbells almost touching the sides of the ribs, shoulder blades squeezing together, chest still on the pad",
            "top position: dumbbells touching the sides of the lower ribs, elbows fully bent and pointing up behind the back, shoulder blades pinched, chest on the pad, feet on the floor",
        ],
        "cue": "Chest glued to the pad, elbows up and back.",
        "notes": "",
    },
    {
        "name": "Inverted Row",
        "aliases": [
            "inverted rows",
            "bodyweight row",
            "bodyweight rows",
            "body row",
            "body rows",
            "australian pull up",
            "australian pullup",
            "australian pull ups",
            "australian pullups",
            "aussie pull up",
            "aussie pullup",
            "ring row",
            "ring rows",
            "trx row",
            "trx rows",
            "suspension row",
            "suspension rows",
            "supine row",
            "supine rows",
            "horizontal pull up",
            "horizontal pullup",
            "horizontal pull ups",
            "horizontal row",
            "horizontal rows",
            "rack row",
            "rack rows",
            "barbell inverted row",
            "smith machine inverted row",
            "feet elevated inverted row",
            "inverted bodyweight row",
        ],
        "category": "upper_pull",
        "camera": "side view, camera at hip height, athlete facing left with the head on the right, lying face up beneath the bar",
        "equipment": "a fixed horizontal bar at hip height gripped overhand slightly wider than the shoulders, the athlete hanging beneath it with the heels on the floor",
        "setting": "a barbell racked at hip height inside a squat rack on a plain gym floor",
        "loop": "pingpong",
        "keyframes": [
            "hanging beneath the bar with arms fully straight, body in a rigid straight line from the heels to the shoulders, heels on the floor with toes up, hips off the floor",
            "shoulder blades pulling together, elbows just beginning to bend, chest rising a hand's width toward the bar, body still straight from heels to shoulders",
            "elbows bent about 45 degrees and pointing toward the floor, chest a forearm's length below the bar, hips in line with the body, heels on the floor",
            "elbows bent 90 degrees with upper arms angled 45 degrees to the torso, chest halfway to the bar, body straight, heels planted",
            "elbows bent past 90 degrees and driving down beside the ribs, chest almost touching the bar, shoulder blades squeezed, hips high in line with the body",
            "top position: chest touching the bar, elbows fully bent and pulled behind the torso, shoulder blades pinched, body straight from heels to head, heels on the floor",
        ],
        "cue": "Body like a plank, pull the chest to the bar.",
        "notes": "",
    },
    {
        "name": "Face Pull",
        "aliases": [
            "face pulls",
            "facepull",
            "facepulls",
            "cable face pull",
            "cable face pulls",
            "rope face pull",
            "rope face pulls",
            "band face pull",
            "band face pulls",
            "banded face pull",
            "banded face pulls",
            "face pull with rope",
            "rope face pull to forehead",
            "high cable face pull",
            "standing face pull",
            "seated face pull",
            "rear delt face pull",
        ],
        "category": "upper_pull",
        "camera": "side view, camera at chest height, athlete facing left toward the cable station on the left edge",
        "equipment": "a rope attachment on a cable pulley set just above head height, gripped with both hands thumbs toward the athlete, the cable running forward and slightly up to the pulley",
        "setting": "a plain gym floor in front of a cable station at the left edge, the athlete standing in a staggered stance",
        "loop": "pingpong",
        "keyframes": [
            "standing in a staggered stance leaning back slightly, arms fully extended forward and up toward the high pulley holding the rope at face height, cable taut, torso upright",
            "elbows beginning to bend and flare outward, rope pulled a hand's width toward the face, upper arms rising level with the shoulders, torso still",
            "elbows bent about 60 degrees and pointing out to the sides at shoulder height, hands a forearm's length in front of the face, shoulder blades drawing together",
            "elbows bent 90 degrees with upper arms in line with the shoulders, hands level with the ears in front of the face, rope ends separating, chest tall",
            "elbows bent past 90 degrees and driving back behind the shoulders, hands beside the ears, forearms angled up, shoulder blades pinched, torso upright",
            "end position: hands beside the ears with the rope ends pulled apart, elbows high and behind the shoulders, forearms pointing up, shoulder blades fully squeezed, torso upright",
        ],
        "cue": "Pull the rope to your ears, elbows high and wide.",
        "notes": "",
    },
    {
        "name": "Rear Delt Fly",
        "aliases": [
            "rear delt flys",
            "rear delt flyes",
            "rear delt flies",
            "rear delt flye",
            "rear delt raise",
            "rear delt raises",
            "rear delts",
            "rear deltoid fly",
            "rear deltoid raise",
            "reverse fly",
            "reverse flys",
            "reverse flyes",
            "reverse flies",
            "reverse flye",
            "bent over fly",
            "bent over flys",
            "bent over flyes",
            "bent over flies",
            "bent over reverse fly",
            "bent over reverse flys",
            "bent over rear delt fly",
            "bent over rear delt flys",
            "bent over rear delt raise",
            "bent over lateral raise",
            "bent over lateral raises",
            "dumbbell rear delt fly",
            "dumbbell rear delt flys",
            "db rear delt fly",
            "db rear delt flys",
            "dumbbell reverse fly",
            "dumbbell reverse flys",
            "db reverse fly",
            "db reverse flys",
            "cable rear delt fly",
            "cable reverse fly",
            "reverse pec deck",
            "reverse pec dec",
            "rear delt machine",
            "rear delt machine fly",
            "machine rear delt fly",
            "machine reverse fly",
            "seated rear delt fly",
            "seated bent over rear delt fly",
            "posterior delt fly",
            "posterior delt raise",
        ],
        "category": "upper_pull",
        "camera": "three-quarter front view, camera at chest height, athlete facing the camera",
        "equipment": "a light dumbbell held in each hand, palms facing each other, elbows slightly bent",
        "setting": "a plain gym floor",
        "loop": "pingpong",
        "keyframes": [
            "hinged at the hips with the torso about 45 degrees from the floor, knees slightly bent, back flat, arms hanging straight down below the shoulders with the dumbbells close together",
            "arms lifting about 15 degrees away from the hanging position, elbows slightly bent, dumbbells drifting apart, torso and knees held still",
            "arms raised about 35 degrees from vertical, elbows slightly bent and leading outward, dumbbells level with the knees, shoulder blades starting to draw together",
            "arms raised about 55 degrees from vertical, elbows slightly bent and pointing toward the ceiling, dumbbells level with the hips, back flat",
            "arms raised about 75 degrees, nearly in line with the shoulders, elbows slightly bent, dumbbells just below shoulder height, torso still at 45 degrees",
            "top position: arms out to the sides in line with the shoulders, slight bend in the elbows, dumbbells level with the shoulders, shoulder blades squeezed, torso still hinged",
        ],
        "cue": "Hinge, lead with the elbows, squeeze the rear delts.",
        "notes": "",
    },
    {
        "name": "Biceps Curl",
        "aliases": [
            "curl",
            "curls",
            "bicep curl",
            "bicep curls",
            "biceps curls",
            "biceps",
            "bicep",
            "arm curl",
            "arm curls",
            "barbell curl",
            "barbell curls",
            "bb curl",
            "bb curls",
            "barbell biceps curl",
            "barbell bicep curl",
            "barbell biceps curls",
            "barbell bicep curls",
            "standing barbell curl",
            "standing barbell curls",
            "straight bar curl",
            "straight bar curls",
            "ez bar curl",
            "ez bar curls",
            "ez curl",
            "ez curls",
            "ez bar biceps curl",
            "ez bar bicep curl",
            "dumbbell curl",
            "dumbbell curls",
            "db curl",
            "db curls",
            "dumbbell biceps curl",
            "dumbbell bicep curl",
            "dumbbell biceps curls",
            "dumbbell bicep curls",
            "standing dumbbell curl",
            "standing dumbbell curls",
            "standing db curl",
            "alternating dumbbell curl",
            "alternating dumbbell curls",
            "alternating curl",
            "alternating curls",
            "alternating db curl",
            "supinated curl",
            "supinated curls",
            "supinating curl",
            "supinating dumbbell curl",
            "cable curl",
            "cable curls",
            "cable biceps curl",
            "cable bicep curl",
            "standing curl",
            "standing curls",
            "standing biceps curl",
            "standing bicep curl",
            "seated dumbbell curl",
            "seated db curl",
            "seated curl",
            "seated curls",
            "strict curl",
            "strict curls",
        ],
        "category": "upper_pull",
        "camera": "side view, camera at hip height, athlete facing left",
        "equipment": "a straight barbell loaded with small round plates held at arm's length in front of the thighs, underhand grip at shoulder width, palms facing forward",
        "setting": "a plain gym floor",
        "loop": "pingpong",
        "keyframes": [
            "standing tall with feet hip-width apart, knees soft, arms fully straight so the bar rests against the front of the thighs, palms facing forward, elbows at the sides",
            "elbows beginning to bend about 25 degrees, bar lifting a hand's width off the thighs, upper arms vertical and pinned to the sides, torso still",
            "elbows bent about 50 degrees, forearms angled up, bar at hip height a forearm's length in front of the body, upper arms vertical",
            "elbows bent 90 degrees with the forearms parallel to the floor, bar level with the navel, upper arms still vertical at the sides, torso upright",
            "elbows bent about 120 degrees, forearms angled up past horizontal, bar at the lower chest, upper arms vertical, wrists straight",
            "top position: elbows fully bent, bar just in front of the upper chest near the shoulders, forearms nearly vertical, upper arms still at the sides, torso upright",
        ],
        "cue": "Elbows pinned, curl slow, lower slower.",
        "notes": "",
    },
    {
        "name": "Hammer Curl",
        "aliases": [
            "hammer curls",
            "hammers",
            "dumbbell hammer curl",
            "dumbbell hammer curls",
            "db hammer curl",
            "db hammer curls",
            "neutral grip curl",
            "neutral grip curls",
            "neutral grip dumbbell curl",
            "neutral grip dumbbell curls",
            "neutral grip db curl",
            "standing hammer curl",
            "standing hammer curls",
            "seated hammer curl",
            "seated hammer curls",
            "alternating hammer curl",
            "alternating hammer curls",
            "rope hammer curl",
            "rope hammer curls",
            "cable hammer curl",
            "cable hammer curls",
            "cross body hammer curl",
            "cross body hammer curls",
            "cross body curl",
            "cross body curls",
            "hammer biceps curl",
            "hammer bicep curl",
        ],
        "category": "upper_pull",
        "camera": "side view, camera at hip height, athlete facing left",
        "equipment": "a dumbbell held in each hand hanging at arm's length at the sides with a neutral grip, palms facing the thighs",
        "setting": "a plain gym floor",
        "loop": "pingpong",
        "keyframes": [
            "standing tall with feet hip-width apart, knees soft, arms fully straight at the sides with the dumbbells hanging vertically beside the thighs, palms facing inward",
            "elbows beginning to bend about 25 degrees, dumbbells lifting a hand's width, thumbs pointing up, upper arms vertical and pinned to the sides",
            "elbows bent about 50 degrees, forearms angled up, dumbbells at hip height in front of the body, palms still facing each other, torso still",
            "elbows bent 90 degrees with the forearms parallel to the floor, dumbbells level with the navel and pointing forward, upper arms vertical at the sides",
            "elbows bent about 120 degrees, forearms angled up past horizontal, dumbbells at the lower chest with thumbs up, upper arms vertical",
            "top position: elbows fully bent, dumbbells held vertically just in front of the shoulders, palms facing each other, upper arms still at the sides, torso upright",
        ],
        "cue": "Thumbs up, elbows still, squeeze at the top.",
        "notes": "",
    },
    {
        "name": "Incline Dumbbell Curl",
        "aliases": [
            "incline dumbbell curls",
            "incline db curl",
            "incline db curls",
            "incline curl",
            "incline curls",
            "incline bench curl",
            "incline bench curls",
            "incline bench dumbbell curl",
            "incline bench dumbbell curls",
            "incline bench db curl",
            "seated incline curl",
            "seated incline curls",
            "seated incline dumbbell curl",
            "seated incline dumbbell curls",
            "incline seated curl",
            "incline seated dumbbell curl",
            "incline biceps curl",
            "incline bicep curl",
            "incline biceps curls",
            "incline bicep curls",
            "incline dumbbell biceps curl",
            "incline dumbbell bicep curl",
            "incline db biceps curl",
            "incline db bicep curl",
            "incline alternating dumbbell curl",
        ],
        "category": "upper_pull",
        "camera": "side view, camera at hip height, athlete facing left",
        "equipment": "a dumbbell held in each hand hanging straight down toward the floor, palms facing forward",
        "setting": "an incline bench set to about 60 degrees on a plain gym floor, the athlete seated with the back and head on the pad and the feet flat on the floor",
        "loop": "pingpong",
        "keyframes": [
            "seated back against the incline pad with feet flat, arms hanging fully straight behind the line of the torso, dumbbells below and behind the shoulders, palms facing forward",
            "elbows beginning to bend about 25 degrees, dumbbells lifting a hand's width, upper arms still hanging vertically behind the torso, shoulders against the pad",
            "elbows bent about 50 degrees, forearms angled up, dumbbells level with the hips, upper arms vertical and still, back on the pad",
            "elbows bent 90 degrees with the forearms parallel to the floor, dumbbells level with the navel, upper arms vertical, palms facing up",
            "elbows bent about 120 degrees, forearms rising past horizontal, dumbbells at the lower chest, upper arms still pointing straight down, wrists straight",
            "top position: elbows fully bent with the upper arms still vertical, dumbbells beside the front of the shoulders, palms facing up, back and head on the pad",
        ],
        "cue": "Let the arms hang back, curl without swinging the elbows.",
        "notes": "",
    },
    {
        "name": "Preacher Curl",
        "aliases": [
            "preacher curls",
            "preacher",
            "preacher bench curl",
            "preacher bench curls",
            "ez bar preacher curl",
            "ez bar preacher curls",
            "ez preacher curl",
            "barbell preacher curl",
            "barbell preacher curls",
            "bb preacher curl",
            "dumbbell preacher curl",
            "dumbbell preacher curls",
            "db preacher curl",
            "db preacher curls",
            "one arm preacher curl",
            "one arm dumbbell preacher curl",
            "single arm preacher curl",
            "single arm dumbbell preacher curl",
            "machine preacher curl",
            "machine preacher curls",
            "preacher curl machine",
            "cable preacher curl",
            "cable preacher curls",
            "scott curl",
            "scott curls",
            "preacher biceps curl",
            "preacher bicep curl",
            "seated preacher curl",
            "spider curl",
            "spider curls",
        ],
        "category": "upper_pull",
        "camera": "side view, camera at hip height, athlete facing left",
        "equipment": "an EZ curl bar loaded with small round plates, underhand grip at shoulder width, the backs of both upper arms resting flat on the sloped pad",
        "setting": "a preacher curl bench on a plain gym floor, the athlete seated behind it with the chest against the top of the pad and the feet flat on the floor",
        "loop": "pingpong",
        "keyframes": [
            "seated with the upper arms resting on the sloped pad, arms fully extended down the slope so the bar hangs at arm's length near the bottom of the pad, torso upright, feet flat",
            "elbows beginning to bend about 25 degrees, bar lifting a hand's width up the slope, upper arms flat on the pad, wrists straight, torso still",
            "elbows bent about 50 degrees, forearms angled up from the pad, bar level with the elbows, upper arms pressed flat on the pad, chest against the pad top",
            "elbows bent 90 degrees, forearms perpendicular to the pad, bar in front of the chest at pad height, upper arms flat and still, feet flat",
            "elbows bent about 120 degrees, forearms rising past perpendicular, bar approaching the chin, upper arms flat on the pad, wrists straight",
            "top position: elbows fully bent with the forearms nearly vertical, bar just in front of the chin, upper arms still flat on the pad, torso upright, feet flat",
        ],
        "cue": "Arms glued to the pad, full stretch at the bottom.",
        "notes": "",
    },
    {
        "name": "Shrug",
        "aliases": [
            "shrugs",
            "shoulder shrug",
            "shoulder shrugs",
            "trap shrug",
            "trap shrugs",
            "traps",
            "standing shrug",
            "standing shrugs",
            "dumbbell shrug",
            "dumbbell shrugs",
            "db shrug",
            "db shrugs",
            "barbell shrug",
            "barbell shrugs",
            "bb shrug",
            "bb shrugs",
            "trap bar shrug",
            "trap bar shrugs",
            "hex bar shrug",
            "hex bar shrugs",
            "kettlebell shrug",
            "kettlebell shrugs",
            "kb shrug",
            "kb shrugs",
            "smith machine shrug",
            "smith machine shrugs",
            "cable shrug",
            "cable shrugs",
            "behind the back shrug",
            "behind the back shrugs",
            "seated shrug",
            "seated dumbbell shrug",
            "dumbbell shoulder shrug",
            "barbell shoulder shrug",
        ],
        "category": "upper_pull",
        "camera": "front view, camera at chest height, athlete facing the camera",
        "equipment": "a heavy dumbbell held in each hand hanging at arm's length at the sides, palms facing the thighs",
        "setting": "a plain gym floor",
        "loop": "pingpong",
        "keyframes": [
            "standing tall with feet hip-width apart, knees soft, arms fully straight at the sides with the dumbbells hanging beside the thighs, shoulders relaxed and low",
            "shoulders beginning to rise a finger's width, arms still straight, dumbbells lifting slightly, neck long, elbows locked, torso upright",
            "shoulders raised about a third of the way toward the ears, arms straight, dumbbells rising in line with the thighs, chest tall, head neutral",
            "shoulders raised halfway toward the ears, traps visibly bunched, arms straight and vertical, dumbbells lifted a hand's width, torso still",
            "shoulders raised most of the way toward the ears, neck appearing shorter, arms straight, dumbbells lifted beside the hips, elbows locked",
            "top position: shoulders lifted as high as possible toward the ears, arms fully straight, dumbbells at their highest beside the hips, torso upright, knees soft",
        ],
        "cue": "Ears to shoulders, arms straight, pause at the top.",
        "notes": "",
    },
    {
        "name": "Straight-arm Pulldown",
        "aliases": [
            "straight arm pulldowns",
            "straight arm pull down",
            "straight arm pull downs",
            "straight arm lat pulldown",
            "straight arm lat pulldowns",
            "straight arm cable pulldown",
            "straight arm cable pulldowns",
            "straight arm rope pulldown",
            "straight arm rope pulldowns",
            "rope straight arm pulldown",
            "stiff arm pulldown",
            "stiff arm pulldowns",
            "stiff arm pull down",
            "stiff arm lat pulldown",
            "standing straight arm pulldown",
            "standing lat pulldown",
            "straight arm cable pullover",
            "cable pullover",
            "cable pullovers",
            "standing cable pullover",
            "lat pullover",
            "lat pullovers",
            "lat sweep",
            "lat sweeps",
            "cable lat sweep",
            "lat prayer",
            "lat prayers",
            "lat pushdown",
            "lat pushdowns",
            "sap",
        ],
        "category": "upper_pull",
        "camera": "side view, camera at hip height, athlete facing left toward the cable station on the left edge",
        "equipment": "a straight bar attachment on a high cable pulley, gripped overhand at shoulder width with both arms straight, the cable running up to the pulley",
        "setting": "a plain gym floor in front of a cable station at the left edge, the athlete standing a stride back from the pulley",
        "loop": "pingpong",
        "keyframes": [
            "standing in a slight forward lean with knees soft, both arms straight and raised in front to head height holding the bar, cable taut and angled up to the pulley",
            "arms still straight sweeping down about 20 degrees, bar level with the forehead a full arm's length in front, shoulders pulling down, torso still",
            "arms straight at about 45 degrees above horizontal, bar at chin height in front of the body, lats engaged, hips hinged slightly, knees soft",
            "arms straight and parallel to the floor, bar level with the chest an arm's length in front, shoulder blades down and back, torso leaning slightly forward",
            "arms straight sweeping below horizontal, bar level with the navel, elbows locked, torso upright, cable still taut",
            "end position: arms straight and pressed against the front of the body, bar touching the thighs, shoulders down and back, torso upright, knees soft",
        ],
        "cue": "Arms locked, sweep the bar down to your thighs.",
        "notes": "",
    },
    {
        "name": "Meadows Row",
        "aliases": [
            "meadows rows",
            "meadow row",
            "meadow rows",
            "meadows landmine row",
            "landmine meadows row",
            "landmine row",
            "landmine rows",
            "one arm landmine row",
            "one arm landmine rows",
            "single arm landmine row",
            "single arm landmine rows",
            "1 arm landmine row",
            "landmine one arm row",
            "landmine single arm row",
            "landmine dumbbell row",
        ],
        "category": "upper_pull",
        "camera": "three-quarter front view, camera at hip height, athlete facing the camera",
        "equipment": "a barbell anchored in a landmine pivot on the floor behind the athlete, the free end loaded with one small round plate, gripped overhand on the end of the sleeve with the right hand",
        "setting": "a plain gym floor, the athlete standing beside the free end of the bar with the body perpendicular to it",
        "loop": "pingpong",
        "keyframes": [
            "staggered stance with the left foot forward, torso hinged about 45 degrees with a flat back, right arm fully straight hanging down to the bar end, left forearm braced on the left thigh",
            "right elbow beginning to bend and flare outward, plate lifting a hand's width off the floor, torso and legs held still, left forearm on the thigh",
            "right elbow bent about 45 degrees and pointing out to the side, bar end level with the knee, forearm vertical, shoulder blade drawing back",
            "right elbow bent 90 degrees and lifted level with the torso, upper arm flared about 45 degrees from the body, bar end at mid-thigh, torso hinged and still",
            "right elbow driving up above the back, bar end approaching the ribs, upper arm flared out, shoulder blade squeezed, left forearm still on the thigh",
            "top position: right elbow high and out to the side above the back, bar end touching the side of the ribs, forearm pointing down, torso still hinged at 45 degrees",
        ],
        "cue": "Elbow high and wide, row the bar end to your ribs.",
        "notes": "Draw the barbell as a straight bar angled up from a floor pivot behind the athlete to the plate at the free end beside the athlete's hip, so the plate rises and falls with the hand.",
    },
    {
        "name": "Dead Hang",
        "aliases": [
            "dead hangs",
            "deadhang",
            "deadhangs",
            "bar hang",
            "bar hangs",
            "passive hang",
            "passive hangs",
            "hang",
            "hangs",
            "hanging",
            "hang from bar",
            "hang from the bar",
            "hanging from bar",
            "hanging from the bar",
            "pull up bar hang",
            "pullup bar hang",
            "dead hang hold",
            "dead hang from bar",
            "timed hang",
            "timed hangs",
            "grip hang",
            "grip hangs",
            "hanging hold",
            "active hang",
            "active hangs",
            "scapular hang",
        ],
        "category": "upper_pull",
        "camera": "side view, camera at chest height, athlete facing left",
        "equipment": "a fixed horizontal pull-up bar high overhead, gripped with an overhand grip just wider than the shoulders, palms facing away",
        "setting": "a low step box on a plain gym floor directly beneath a high pull-up bar",
        "loop": "pingpong",
        "keyframes": [
            "standing tall on top of the box directly beneath the bar, both arms reaching up gripping the bar overhand, elbows bent about 45 degrees, feet flat, torso upright",
            "knees bending about 30 degrees and hips sinking, elbows straightening to about 20 degrees, weight shifting from the feet into the hands, heels lifting off the box",
            "feet just leaving the box, arms nearly straight, knees bent about 60 degrees with the feet trailing behind, shoulders rising toward the ears, torso vertical",
            "hanging from the bar with arms straight, knees bent 90 degrees so the shins are horizontal and the feet tucked behind, shoulders still slightly packed down",
            "hanging with arms fully straight, knees bent 90 degrees, ankles crossing behind, shoulders relaxing upward toward the ears, torso vertical and still",
            "dead hang: arms fully extended, shoulders relaxed up by the ears, torso vertical, knees bent 90 degrees with the ankles crossed and feet tucked behind, feet clear of the box",
        ],
        "cue": "Relax the shoulders, grip hard, breathe.",
        "notes": "The bar stays high overhead and the box stays in the same place beneath the athlete in every panel; once the feet leave the box they never touch it or the floor again.",
    },
    {
        "name": "Band Pull-apart",
        "aliases": [
            "band pull aparts",
            "band pullapart",
            "band pullaparts",
            "pull apart",
            "pull aparts",
            "pullapart",
            "pullaparts",
            "resistance band pull apart",
            "resistance band pull aparts",
            "banded pull apart",
            "banded pull aparts",
            "rear delt band pull apart",
            "mini band pull apart",
            "light band pull apart",
            "band pull apart at chest height",
            "band pull a part",
            "band pull a parts",
            "pull apart band",
            "band pull apart hold",
            "band pull aparts hold",
        ],
        "category": "upper_pull",
        "camera": "three-quarter front view, camera at chest height, athlete facing the camera",
        "equipment": "a light resistance band held taut between both hands with an overhand grip, palms facing down, arms straight",
        "setting": "a plain gym floor",
        "loop": "pingpong",
        "keyframes": [
            "standing tall with feet hip-width apart, both arms straight and extended forward at shoulder height, hands shoulder-width apart holding the band taut in front of the chest",
            "arms still straight sweeping outward about 20 degrees, band stretching slightly wider than the shoulders, shoulder blades beginning to draw together, torso still",
            "arms straight and about 45 degrees out from the front, band stretched well beyond shoulder width, palms facing down, chest lifting, elbows locked",
            "arms straight and about 60 degrees out to the sides, band stretched wide across the front of the chest, shoulder blades squeezing, torso upright",
            "arms straight and nearly in line with the shoulders, band almost touching the chest, palms facing down, shoulders down and back, elbows locked",
            "end position: arms straight out to the sides in a T with the band stretched against the chest, shoulder blades fully squeezed, palms facing down, torso upright",
        ],
        "cue": "Arms straight, pull the band to your chest.",
        "notes": "",
    },
]
