"""Upper-body pushing movements: horizontal and vertical presses, dips, raises and triceps work.

Every movement here is symmetric (the way down mirrors the way up), so all entries use
``loop: "pingpong"`` and the keyframes describe ONE direction only:

* presses: from the start/rack position to the furthest point (bar on chest, or lockout overhead)
* raises and extensions: from the resting position to the top of the range
* push-up, dip, pike push-up: from the top support position down to the bottom

Cameras are fixed per exercise. Lying movements are drawn from the side at bench height with the
head at the left end of the bench; standing movements are side view with the athlete facing left
unless both arms need to be visible (lateral raise, shoulder press, Arnold press), which use a
front view with the athlete facing the camera.
"""

_SIDE = "side view, camera at hip height, athlete facing left"
_FRONT = "front view, camera at chest height, athlete facing the camera"
_BENCH_SIDE = (
    "side view, camera level with the bench, athlete lying on their back with the head at the left "
    "end of the bench, near side of the body facing the camera"
)
_INCLINE_SIDE = (
    "side view, camera level with the bench pad, athlete lying back on the incline bench with the "
    "head at the left end, near side of the body facing the camera"
)

_BARBELL_WIDE = (
    "a barbell loaded with round plates held in both hands with an overhand grip slightly wider "
    "than the shoulders"
)
_FRONT_RACK_BARBELL = (
    "a barbell loaded with round plates held in a front-rack position on the front of the shoulders, "
    "overhand grip just outside the shoulders"
)

EXERCISES = [
    # -- horizontal presses --------------------------------------------------------------
    {
        "name": "Bench Press",
        "aliases": [
            "bench",
            "barbell bench press",
            "flat bench press",
            "flat barbell bench press",
            "flat bench",
            "barbell bench",
            "bb bench press",
            "bb bench",
            "bench presses",
            "flat barbell press",
            "barbell chest press",
        ],
        "category": "upper_push",
        "camera": _BENCH_SIDE,
        "equipment": _BARBELL_WIDE,
        "setting": "a flat bench inside a bench-press rack on a plain gym floor",
        "loop": "pingpong",
        "keyframes": [
            "lying flat on the bench, feet flat on the floor, barbell held at arm's length directly above the shoulders, elbows locked, wrists straight",
            "elbows starting to bend about 20 degrees, bar lowered a hand's width from lockout and still above the upper chest, feet flat, back on the bench",
            "elbows bent about 45 degrees, bar halfway down toward the chest, forearms vertical, upper arms angled about 45 degrees away from the torso",
            "elbows bent about 70 degrees, bar a fist's height above the lower chest, elbows dropping below the level of the bench, shoulder blades pinched",
            "elbows bent about 85 degrees, bar just above the chest, forearms still vertical, slight arch in the lower back, feet pressing into the floor",
            "bottom position: barbell lightly touching the lower chest, elbows bent about 90 degrees and tucked 45 degrees from the torso, forearms vertical, feet flat",
        ],
        "cue": "Feet planted, bar to lower chest, press to lockout.",
        "notes": "",
    },
    {
        "name": "Incline Bench Press",
        "aliases": [
            "incline bench",
            "incline barbell bench",
            "incline barbell bench press",
            "incline barbell press",
            "barbell incline press",
            "barbell incline bench press",
            "incline press",
            "incline bb bench",
            "incline bb bench press",
            "incline bench presses",
        ],
        "category": "upper_push",
        "camera": _INCLINE_SIDE,
        "equipment": _BARBELL_WIDE,
        "setting": "an incline bench set to about 30 degrees inside a rack on a plain gym floor",
        "loop": "pingpong",
        "keyframes": [
            "lying back on the incline bench, feet flat on the floor, barbell held at arm's length straight above the shoulders, elbows locked, head on the pad",
            "elbows bending about 20 degrees, bar lowered a hand's width and still directly above the upper chest, head and hips resting on the bench",
            "elbows bent about 45 degrees, bar halfway to the chest, forearms vertical, upper arms about 45 degrees away from the torso, feet flat",
            "elbows bent about 70 degrees, bar a fist's height above the upper chest, elbows dropping below the bench pad, chest lifted toward the bar",
            "elbows bent about 85 degrees, bar just above the collarbones, forearms vertical, shoulder blades pinched against the pad, feet flat",
            "bottom position: barbell touching the upper chest just below the collarbones, elbows bent about 90 degrees, forearms vertical, feet flat on the floor",
        ],
        "cue": "Bar to upper chest, elbows under the bar, drive up.",
        "notes": "",
    },
    {
        "name": "Dumbbell Bench Press",
        "aliases": [
            "db bench press",
            "db bench",
            "dumbbell bench",
            "flat dumbbell press",
            "flat dumbbell bench press",
            "flat db press",
            "flat db bench press",
            "dumbbell chest press",
            "db chest press",
            "dumbbell bench presses",
        ],
        "category": "upper_push",
        "camera": _BENCH_SIDE,
        "equipment": "a pair of dumbbells held one in each hand with an overhand grip, palms facing the feet",
        "setting": "a flat bench on a plain gym floor",
        "loop": "pingpong",
        "keyframes": [
            "lying flat on the bench, feet flat on the floor, both dumbbells pressed to arm's length above the shoulders and nearly touching, elbows locked",
            "elbows bending about 20 degrees, dumbbells lowered a hand's width and drifting slightly apart, still above the chest, feet flat",
            "elbows bent about 45 degrees, dumbbells halfway down and shoulder-width apart, forearms vertical, upper arms about 45 degrees from the torso",
            "elbows bent about 70 degrees, dumbbells level with the top of the chest, elbows dropping below the bench, shoulder blades pinched together",
            "elbows bent about 85 degrees, dumbbells just above chest height beside the torso, forearms vertical, feet pressing into the floor",
            "bottom position: dumbbells level with the chest beside the torso, elbows bent about 90 degrees and slightly below the bench, forearms vertical, feet flat",
        ],
        "cue": "Elbows under the bells, press up and slightly together.",
        "notes": "",
    },
    {
        "name": "Incline Dumbbell Press",
        "aliases": [
            "incline db press",
            "incline dumbbell bench press",
            "dumbbell incline press",
            "dumbbell incline bench press",
            "incline db bench press",
            "db incline press",
            "db incline bench press",
            "incline dumbbell bench",
            "incline db bench",
            "incline dumbbell chest press",
            "incline db chest press",
            "incline dumbbell presses",
        ],
        "category": "upper_push",
        "camera": _INCLINE_SIDE,
        "equipment": "a pair of dumbbells held one in each hand with an overhand grip, palms facing forward and up",
        "setting": "an incline bench set to about 30 degrees on a plain gym floor",
        "loop": "pingpong",
        "keyframes": [
            "lying back on the incline bench, feet flat on the floor, both dumbbells pressed to arm's length above the shoulders and nearly touching, elbows locked",
            "elbows bending about 20 degrees, dumbbells lowered a hand's width and drifting slightly apart, still above the upper chest, head on the pad",
            "elbows bent about 45 degrees, dumbbells halfway down and shoulder-width apart, forearms vertical, upper arms about 45 degrees from the torso",
            "elbows bent about 70 degrees, dumbbells level with the top of the chest, elbows dropping below the bench pad, shoulder blades pinched together",
            "elbows bent about 85 degrees, dumbbells just above collarbone height beside the upper chest, forearms vertical, feet pressing into the floor",
            "bottom position: dumbbells level with the upper chest beside the shoulders, elbows bent about 90 degrees and slightly below the pad, forearms vertical, feet flat",
        ],
        "cue": "Bells to the upper chest, press up and together.",
        "notes": "",
    },
    {
        "name": "Close-grip Bench Press",
        "aliases": [
            "close grip bench",
            "cgbp",
            "close grip press",
            "narrow grip bench press",
            "narrow grip bench",
            "cg bench press",
            "cg bench",
            "close grip barbell bench press",
            "close grip bench presses",
        ],
        "category": "upper_push",
        "camera": _BENCH_SIDE,
        "equipment": "a barbell loaded with round plates held with an overhand grip at shoulder width, hands close together",
        "setting": "a flat bench inside a bench-press rack on a plain gym floor",
        "loop": "pingpong",
        "keyframes": [
            "lying flat on the bench, feet flat on the floor, barbell held at arm's length above the shoulders with the hands shoulder-width apart, elbows locked",
            "elbows bending about 20 degrees and staying close to the ribs, bar lowered a hand's width and still above the lower chest, feet flat",
            "elbows bent about 45 degrees and tucked about 20 degrees from the torso, bar halfway to the chest, forearms vertical, back on the bench",
            "elbows bent about 70 degrees and brushing the sides of the torso, bar a fist's height above the lower chest, shoulder blades pinched",
            "elbows bent about 85 degrees, bar just above the lower chest, elbows level with the bench, forearms vertical, feet pressing into the floor",
            "bottom position: barbell touching the lower chest, elbows bent past 90 degrees and tucked against the ribs, forearms vertical, feet flat",
        ],
        "cue": "Hands shoulder-width, elbows tucked, bar to lower chest.",
        "notes": "The hands are noticeably closer together than in a normal bench press and the elbows stay tight to the ribs.",
    },
    {
        "name": "Machine Chest Press",
        "aliases": [
            "chest press",
            "chest presses",
            "chest press machine",
            "seated chest press",
            "seated machine chest press",
            "seated chest press machine",
            "machine press",
            "machine bench press",
            "machine bench",
            "hammer strength chest press",
            "plate loaded chest press",
            "machine chest presses",
            "chest machine press",
        ],
        "category": "upper_push",
        "camera": "side view, camera at chest height, athlete facing left",
        "equipment": "a seated chest-press machine with a weight stack, both hands gripping the horizontal handles at chest height",
        "setting": "a seated chest-press machine on a plain gym floor, the athlete seated with the back against the pad",
        "loop": "pingpong",
        "keyframes": [
            "seated upright with the back flat against the pad, feet flat on the floor, hands gripping the handles at mid-chest height, elbows bent about 90 degrees and pointing back",
            "handles pushed a hand's width forward, elbows bent about 75 degrees and level with the shoulders, back against the pad, shoulders down",
            "handles halfway out, elbows bent about 60 degrees, forearms horizontal, upper arms angled about 45 degrees from the torso, head against the pad",
            "handles three-quarters extended, elbows bent about 40 degrees, wrists straight in line with the forearms, back and head still on the pad",
            "elbows bent about 20 degrees, handles nearly at full reach in front of the chest, shoulders staying back against the pad, feet flat",
            "end position: both arms extended straight in front of the chest with the elbows almost locked, handles at full reach, shoulder blades still on the pad, feet flat",
        ],
        "cue": "Shoulders back on the pad, press out, control the return.",
        "notes": "",
    },
    {
        "name": "Chest Fly",
        "aliases": [
            "chest flys",
            "chest flyes",
            "chest flies",
            "chest flye",
            "dumbbell fly",
            "dumbbell flys",
            "dumbbell flyes",
            "dumbbell flies",
            "dumbbell flye",
            "db fly",
            "db flys",
            "db flyes",
            "db flies",
            "pec fly",
            "pec flys",
            "pec flyes",
            "pec flies",
            "pec flye",
            "flat dumbbell fly",
            "flat dumbbell flys",
            "flat dumbbell flyes",
            "flat db fly",
            "flat bench fly",
            "flat fly",
            "flat flys",
            "flat flyes",
            "dumbbell chest fly",
            "dumbbell chest flys",
            "dumbbell chest flyes",
            "db chest fly",
            "db chest flys",
            "db chest flyes",
        ],
        "category": "upper_push",
        "camera": (
            "three-quarter view from the foot of the bench, camera slightly above bench height, athlete lying "
            "on their back with the feet nearest the camera and the head farthest away, chest facing the camera"
        ),
        "equipment": "a pair of dumbbells held one in each hand with a neutral grip, palms facing each other",
        "setting": "a flat bench on a plain gym floor",
        "loop": "pingpong",
        "keyframes": [
            "lying flat on the bench, feet flat on the floor, dumbbells held together at arm's length above the chest, palms facing each other, elbows slightly bent",
            "arms opening about 20 degrees to each side, dumbbells a shoulder-width apart above the chest, elbows slightly bent and fixed, palms facing each other",
            "arms opened about 45 degrees from vertical, dumbbells wide above the shoulders, elbows fixed at a slight bend, chest lifted, shoulder blades pinched",
            "arms opened about 65 degrees, dumbbells at shoulder height out to the sides, elbows slightly bent and pointing toward the floor, feet flat",
            "arms just above horizontal, dumbbells nearly level with the bench, elbows slightly bent, palms facing up and inward, chest stretched open",
            "bottom position: arms wide open in a shallow arc with the dumbbells level with the chest just below bench height, elbows slightly bent, palms facing up",
        ],
        "cue": "Soft elbows, open wide, squeeze the dumbbells back together.",
        "notes": "Both arms must stay fully visible in every panel; the elbow bend never changes, only the shoulder angle.",
    },
    # -- vertical presses ----------------------------------------------------------------
    {
        "name": "Overhead Press",
        "aliases": [
            "ohp",
            "military press",
            "barbell overhead press",
            "standing barbell press",
            "standing overhead press",
            "strict press",
            "strict overhead press",
            "barbell shoulder press",
            "barbell press",
            "standing press",
            "standing military press",
            "barbell military press",
            "overhead presses",
            "bb ohp",
            "bb overhead press",
        ],
        "category": "upper_push",
        "camera": _SIDE,
        "equipment": _FRONT_RACK_BARBELL,
        "setting": "a plain gym floor in front of a squat rack",
        "loop": "pingpong",
        "keyframes": [
            "standing upright, feet hip-width apart, knees straight, barbell resting on the front of the shoulders at collarbone height, elbows slightly in front of the bar, forearms vertical",
            "bar pressed a hand's width above the shoulders, elbows bent about 90 degrees and pointing forward, chin tucked back slightly, torso upright",
            "bar at nose height passing close to the face, elbows bent about 60 degrees, head tilted slightly back, hips pushed a little forward",
            "bar just above the forehead, elbows bent about 40 degrees, head starting to move forward under the bar, torso vertical, knees straight",
            "bar above the crown of the head, elbows nearly straight, head pushed forward through the arms, ribs down, knees straight",
            "lockout: barbell held overhead at full arm extension directly over the midfoot, elbows locked, head through the arms, torso and legs vertical",
        ],
        "cue": "Squeeze glutes, press up, head through at the top.",
        "notes": "",
    },
    {
        "name": "Dumbbell Shoulder Press",
        "aliases": [
            "shoulder press",
            "shoulder presses",
            "db shoulder press",
            "seated dumbbell press",
            "seated db press",
            "dumbbell overhead press",
            "db overhead press",
            "db ohp",
            "dumbbell ohp",
            "seated dumbbell shoulder press",
            "seated db shoulder press",
            "seated shoulder press",
            "seated dumbbell overhead press",
            "dumbbell military press",
            "dumbbell shoulder presses",
        ],
        "category": "upper_push",
        "camera": _FRONT,
        "equipment": "a pair of dumbbells held one in each hand with an overhand grip, palms facing forward",
        "setting": "seated on an upright bench with a back pad on a plain gym floor",
        "loop": "pingpong",
        "keyframes": [
            "seated upright with the back against the pad, feet flat, dumbbells at shoulder height beside the head, elbows bent about 90 degrees and out to the sides, palms forward",
            "dumbbells pressed a hand's width above the shoulders, elbows bent about 70 degrees and pointing out to the sides, torso upright, feet flat",
            "dumbbells at ear height, elbows bent about 50 degrees, forearms vertical, upper arms angled about 30 degrees above horizontal, shoulders down",
            "dumbbells above head height, elbows bent about 30 degrees, arms forming a wide V, shoulders down, back still against the pad",
            "dumbbells nearly at full extension, elbows slightly bent, dumbbells drifting toward each other above the head, torso upright against the pad",
            "lockout: both arms fully extended overhead with the dumbbells nearly touching above the crown of the head, elbows straight, torso upright, feet flat",
        ],
        "cue": "Press up and in, don't shrug the shoulders.",
        "notes": "",
    },
    {
        "name": "Push Press",
        "aliases": [
            "push presses",
            "barbell push press",
            "bb push press",
            "dumbbell push press",
            "db push press",
        ],
        "category": "upper_push",
        "camera": _SIDE,
        "equipment": _FRONT_RACK_BARBELL,
        "setting": "a plain gym floor in front of a squat rack",
        "loop": "pingpong",
        "keyframes": [
            "standing upright, feet hip-width apart, knees straight, barbell in the front-rack position on the shoulders, elbows slightly in front of the bar, forearms vertical",
            "shallow dip: knees bent about 20 degrees, torso vertical, hips dropping straight down, bar still resting on the shoulders, heels flat on the floor",
            "drive: knees and hips snapping straight, heels rising slightly off the floor, bar just leaving the shoulders at chin height, elbows bent about 90 degrees",
            "bar at forehead height, legs straight, heels back on the floor, elbows bent about 50 degrees, head tilted slightly back, torso vertical",
            "bar above the crown of the head, elbows nearly straight, head pushed forward through the arms, torso vertical, knees straight",
            "lockout: barbell overhead at full arm extension over the midfoot, elbows locked, head through the arms, legs and torso vertical",
        ],
        "cue": "Dip straight down, drive with the legs, punch to lockout.",
        "notes": "Panel 2 is the only panel with bent knees; the torso stays vertical throughout the dip.",
    },
    {
        "name": "Arnold Press",
        "aliases": [
            "arnold presses",
            "arnolds",
            "seated arnold press",
            "dumbbell arnold press",
            "db arnold press",
            "standing arnold press",
        ],
        "category": "upper_push",
        "camera": _FRONT,
        "equipment": "a pair of dumbbells held one in each hand",
        "setting": "seated on an upright bench with a back pad on a plain gym floor",
        "loop": "pingpong",
        "keyframes": [
            "seated upright on the bench, feet flat, dumbbells held in front of the shoulders at chin height with palms facing the face, elbows bent and pointing down in front of the ribs",
            "dumbbells lifted to eye height and starting to swing outward, elbows bent about 90 degrees and moving out to the sides, palms turning to face each other",
            "dumbbells at ear height beside the head, elbows bent about 90 degrees and pointing out to the sides, palms now facing forward, torso upright",
            "dumbbells pressed just above head height, elbows bent about 60 degrees, palms forward, arms forming a wide V, feet flat on the floor",
            "dumbbells nearly at full extension, elbows slightly bent, dumbbells drifting toward each other above the head, palms forward, torso upright",
            "lockout: arms fully extended overhead with the dumbbells almost touching above the crown of the head, palms forward, elbows straight, back against the pad",
        ],
        "cue": "Rotate palms out as you press, lock out overhead.",
        "notes": "The palms rotate from facing the athlete in panel 1 to facing forward by panel 3; draw the hands clearly.",
    },
    {
        "name": "Landmine Press",
        "aliases": [
            "landmine presses",
            "landmine shoulder press",
            "landmine overhead press",
            "single arm landmine press",
            "one arm landmine press",
            "standing landmine press",
            "half kneeling landmine press",
        ],
        "category": "upper_push",
        "camera": _SIDE,
        "equipment": (
            "a barbell with one end anchored in a landmine sleeve on the floor and one round plate on the free end, "
            "the free end held in the left hand nearest the camera"
        ),
        "setting": "a plain gym floor with the landmine base on the floor at the left of the frame",
        "loop": "pingpong",
        "keyframes": [
            "standing in a staggered stance facing the landmine, right foot forward, bar end held in the left hand at the front of the shoulder, elbow bent and tucked, torso upright",
            "bar end pressed a hand's width up and forward, elbow bent about 90 degrees, torso starting to lean forward from the hips, back heel raised",
            "bar end at chin height, elbow bent about 60 degrees and behind the bar, torso leaning forward about 15 degrees, front knee softly bent",
            "bar end at eye height, elbow bent about 40 degrees, arm angled 45 degrees up and forward along the bar, hips square to the landmine",
            "bar end above head height, elbow nearly straight, arm reaching forward and up in line with the bar, torso leaning forward about 15 degrees",
            "lockout: arm fully extended along the bar at about 45 degrees up and forward, elbow locked, shoulder reaching forward, torso leaning slightly forward, staggered stance",
        ],
        "cue": "Press up and forward, reach the shoulder at the top.",
        "notes": "The bar always runs in a straight line from the landmine base on the floor up to the hand; only one arm holds the bar.",
    },
    # -- bodyweight pushes ---------------------------------------------------------------
    {
        "name": "Push-up",
        "aliases": [
            "pushup",
            "push up",
            "pushups",
            "push ups",
            "push-ups",
            "press up",
            "press ups",
            "press-up",
            "press-ups",
            "standard push up",
            "standard pushup",
            "regular push up",
            "bodyweight push up",
        ],
        "category": "upper_push",
        "camera": "side view, camera at knee height, athlete facing left with the head at the left of the frame",
        "equipment": "no equipment",
        "setting": "a plain gym floor",
        "loop": "pingpong",
        "keyframes": [
            "high plank: hands flat on the floor under the shoulders, arms locked, body a straight line from head to heels, toes tucked, eyes looking at the floor",
            "elbows bending about 20 degrees and angling back about 45 degrees from the torso, body still one straight line, chest lowering slightly",
            "elbows bent about 45 degrees, chest halfway to the floor, upper arms angled back, body rigid from shoulders to heels, hips not sagging",
            "elbows bent about 70 degrees, chest a fist's height above the floor, forearms vertical, elbows pointing back and out, body straight",
            "elbows bent about 85 degrees, chest just above the floor, upper arms nearly parallel to the floor, body one straight line from head to heels",
            "bottom position: chest a few centimetres above the floor, elbows bent about 90 degrees, forearms vertical, body still straight from head to heels, toes tucked",
        ],
        "cue": "Body straight, elbows back, chest to the floor.",
        "notes": "The body is horizontal, so the figure is wider than tall; keep the whole body from hands to toes inside every panel.",
    },
    {
        "name": "Pike Push-up",
        "aliases": [
            "pike pushup",
            "pike pushups",
            "pike push ups",
            "pike push-ups",
            "pike press",
            "pike presses",
            "pike press up",
            "pike press ups",
            "pike press-ups",
            "elevated pike push up",
            "elevated pike pushup",
            "feet elevated pike push up",
            "feet elevated pike pushup",
        ],
        "category": "upper_push",
        "camera": "side view, camera at knee height, athlete facing left with the hands at the left of the frame and the feet at the right",
        "equipment": "no equipment",
        "setting": "a plain gym floor",
        "loop": "pingpong",
        "keyframes": [
            "inverted V: hands flat on the floor shoulder-width apart, hips pushed high, legs straight, feet flat behind, arms locked, head between the arms looking at the feet",
            "elbows bending about 20 degrees, hips staying high, head lowering toward the floor in front of the hands, legs straight, heels lifting slightly",
            "elbows bent about 45 degrees, crown of the head halfway to the floor, hips still high above the shoulders, torso vertical, legs straight",
            "elbows bent about 70 degrees and pointing back at 45 degrees, head a fist's height above the floor, forearms vertical, hips high",
            "elbows bent about 85 degrees, crown of the head just above the floor slightly in front of the hands, torso vertical, hips over the shoulders",
            "bottom position: crown of the head nearly touching the floor just in front of the hands, elbows bent about 90 degrees, hips high, legs straight",
        ],
        "cue": "Hips high, head to the floor, press back to the pike.",
        "notes": "The hips stay at the highest point in every panel; only the arms bend and the head travels down.",
    },
    {
        "name": "Dip",
        "aliases": [
            "dip",
            "dips",
            "parallel bar dip",
            "parallel bar dips",
            "bar dip",
            "bar dips",
            "chest dip",
            "chest dips",
            "triceps dip",
            "triceps dips",
            "tricep dip",
            "tricep dips",
            "ring dip",
            "ring dips",
            "weighted dip",
            "weighted dips",
            "bodyweight dip",
            "bodyweight dips",
        ],
        "category": "upper_push",
        "camera": _SIDE,
        "equipment": "no equipment, bodyweight only",
        "setting": "hanging between two parallel dip bars at chest height on a plain gym floor",
        "loop": "pingpong",
        "keyframes": [
            "top support: arms locked straight on the parallel bars, body hanging vertically between them, knees bent about 90 degrees with the feet crossed behind, chest up",
            "elbows bending about 20 degrees, body lowering slightly, torso starting to lean forward about 10 degrees, knees bent with the feet behind",
            "elbows bent about 45 degrees, body halfway down, torso leaning forward about 15 degrees, shoulders still above the bars, knees bent",
            "elbows bent about 70 degrees and pointing straight back, shoulders level with the bars, torso leaning forward about 20 degrees, feet crossed behind",
            "elbows bent about 85 degrees, shoulders just below the bars, upper arms nearly parallel to the floor, torso leaning forward, knees bent",
            "bottom position: elbows bent about 90 degrees, upper arms parallel to the floor, shoulders below the bars, torso leaning forward about 20 degrees, feet crossed behind",
        ],
        "cue": "Lean slightly forward, lower under control, press to lockout.",
        "notes": "Draw both parallel bars at the same height in every panel; the feet never touch the floor.",
    },
    # -- shoulder raises -----------------------------------------------------------------
    {
        "name": "Lateral Raise",
        "aliases": [
            "lateral raises",
            "side raise",
            "side raises",
            "side lateral raise",
            "side lateral raises",
            "dumbbell lateral raise",
            "dumbbell lateral raises",
            "db lateral raise",
            "db lateral raises",
            "db lat raise",
            "lat raise",
            "lat raises",
            "dumbbell side raise",
            "dumbbell side raises",
            "cable lateral raise",
            "lateral delt raise",
            "side delt raise",
            "standing lateral raise",
            "lateral shoulder raise",
        ],
        "category": "upper_push",
        "camera": _FRONT,
        "equipment": "a pair of light dumbbells held one in each hand with a neutral grip, palms facing the thighs",
        "setting": "a plain gym floor",
        "loop": "pingpong",
        "keyframes": [
            "standing upright facing the camera, feet hip-width apart, knees soft, dumbbells hanging at the sides of the thighs, arms straight, palms facing inward",
            "dumbbells lifted about 20 degrees out to the sides, elbows slightly bent, torso upright, shoulders down, dumbbells clear of the thighs",
            "arms raised about 45 degrees from the body, elbows slightly bent, dumbbells level with the waist, palms facing down, torso still upright",
            "arms raised about 65 degrees, dumbbells at chest height out to the sides, elbows slightly bent and higher than the wrists, shoulders down",
            "arms just below horizontal, dumbbells nearly at shoulder height, elbows slightly bent, palms facing the floor, torso upright, knees soft",
            "top position: both arms horizontal out to the sides in a T shape, dumbbells at shoulder height, elbows slightly bent, palms down, torso upright",
        ],
        "cue": "Lead with the elbows, raise to shoulder height, lower slowly.",
        "notes": "",
    },
    {
        "name": "Front Raise",
        "aliases": [
            "front raises",
            "dumbbell front raise",
            "dumbbell front raises",
            "db front raise",
            "db front raises",
            "plate front raise",
            "plate raise",
            "plate raises",
            "barbell front raise",
            "cable front raise",
            "front delt raise",
            "front shoulder raise",
            "anterior raise",
            "standing front raise",
            "alternating front raise",
        ],
        "category": "upper_push",
        "camera": _SIDE,
        "equipment": "a pair of dumbbells held one in each hand with an overhand grip, palms facing the thighs",
        "setting": "a plain gym floor",
        "loop": "pingpong",
        "keyframes": [
            "standing upright, feet hip-width apart, knees soft, dumbbells resting against the front of the thighs, arms straight, palms facing the thighs",
            "dumbbells lifted about 20 degrees in front of the body, arms straight with a slight elbow bend, torso upright, shoulders down",
            "arms raised about 45 degrees in front, dumbbells at waist height, elbows slightly bent, palms facing the floor, torso upright",
            "arms raised about 65 degrees, dumbbells at chest height in front of the body, elbows slightly bent, chest up, no lean back",
            "arms just below horizontal, dumbbells nearly at shoulder height in front of the body, palms down, torso upright, knees soft",
            "top position: both arms horizontal straight out in front at shoulder height, dumbbells level with the shoulders, elbows slightly bent, torso upright",
        ],
        "cue": "Raise to shoulder height without swinging, lower slowly.",
        "notes": "",
    },
    # -- triceps -------------------------------------------------------------------------
    {
        "name": "Triceps Pushdown",
        "aliases": [
            "tricep pushdown",
            "triceps pushdowns",
            "tricep pushdowns",
            "triceps push down",
            "tricep push down",
            "cable pushdown",
            "cable pushdowns",
            "cable push down",
            "rope pushdown",
            "rope pushdowns",
            "rope push down",
            "pushdown",
            "pushdowns",
            "triceps pressdown",
            "tricep pressdown",
            "triceps pressdowns",
            "tricep pressdowns",
            "pressdown",
            "pressdowns",
            "cable triceps pushdown",
            "cable tricep pushdown",
            "rope triceps pushdown",
            "rope tricep pushdown",
            "triceps rope pushdown",
            "tricep rope pushdown",
            "straight bar pushdown",
            "v bar pushdown",
            "cable triceps extension",
            "cable tricep extension",
            "rope triceps extension",
            "rope tricep extension",
        ],
        "category": "upper_push",
        "camera": _SIDE,
        "equipment": "a cable machine with a rope attachment gripped in both hands, palms facing each other, the cable running up to a high pulley",
        "setting": "standing a step back from a tall cable machine on a plain gym floor, the high pulley above head height at the left",
        "loop": "pingpong",
        "keyframes": [
            "standing upright a step back from the cable machine, feet hip-width apart, slight forward lean, elbows bent about 90 degrees pinned at the sides, hands gripping the rope at chest height",
            "elbows bent about 75 degrees, hands pushed down to the bottom of the ribs, elbows still pinned at the sides, torso leaning forward about 10 degrees",
            "elbows bent about 60 degrees, hands at navel height, forearms angled down, upper arms vertical and still, knees soft, torso still",
            "elbows bent about 40 degrees, hands at hip height, rope ends starting to pull apart, elbows tight to the ribs, torso unmoved",
            "elbows bent about 20 degrees, hands beside the thighs, rope ends splitting to either side, upper arms unmoved, torso leaning forward slightly",
            "end position: arms fully straight with the elbows locked at the sides, hands at the front of the thighs, rope ends pulled apart, torso leaning forward about 10 degrees",
        ],
        "cue": "Elbows pinned, push down and split the rope.",
        "notes": "The upper arms stay vertical and glued to the ribs in every panel; only the forearms move.",
    },
    {
        "name": "Skull Crusher",
        "aliases": [
            "skull crushers",
            "skullcrusher",
            "skullcrushers",
            "lying triceps extension",
            "lying tricep extension",
            "lying triceps extensions",
            "lying tricep extensions",
            "ez bar skull crusher",
            "ez bar skull crushers",
            "dumbbell skull crusher",
            "dumbbell skull crushers",
            "db skull crusher",
            "db skull crushers",
            "barbell skull crusher",
            "barbell skull crushers",
            "lying ez bar triceps extension",
            "lying barbell triceps extension",
            "lying dumbbell triceps extension",
            "nose breaker",
            "nose breakers",
        ],
        "category": "upper_push",
        "camera": _BENCH_SIDE,
        "equipment": "an EZ curl bar loaded with small round plates held with a narrow overhand grip",
        "setting": "a flat bench on a plain gym floor",
        "loop": "pingpong",
        "keyframes": [
            "lying flat on the bench, feet flat on the floor, EZ bar held at arm's length straight above the shoulders, elbows locked, upper arms vertical",
            "elbows bending about 20 degrees, bar drifting back toward the head, upper arms tilted slightly back past vertical, elbows pointing at the ceiling",
            "elbows bent about 45 degrees, bar above the top of the head, upper arms still nearly vertical and shoulder-width apart, forearms angled back",
            "elbows bent about 70 degrees, bar a hand's width above the forehead, upper arms fixed and tilted slightly back, elbows kept narrow",
            "elbows bent about 85 degrees, bar just above the forehead, forearms nearly horizontal, upper arms unmoved, feet flat on the floor",
            "bottom position: bar an inch above the forehead, elbows bent about 90 degrees and pointing at the ceiling, upper arms fixed just past vertical, feet flat",
        ],
        "cue": "Elbows fixed, lower to the forehead, extend to lockout.",
        "notes": "The upper arms stay in the same place in every panel; only the forearms hinge at the elbow.",
    },
    {
        "name": "Overhead Triceps Extension",
        "aliases": [
            "overhead tricep extension",
            "overhead triceps extensions",
            "overhead tricep extensions",
            "overhead extension",
            "overhead extensions",
            "triceps extension",
            "tricep extension",
            "triceps extensions",
            "tricep extensions",
            "dumbbell overhead triceps extension",
            "dumbbell overhead tricep extension",
            "db overhead triceps extension",
            "db overhead tricep extension",
            "db overhead extension",
            "dumbbell overhead extension",
            "overhead dumbbell extension",
            "overhead dumbbell triceps extension",
            "overhead db extension",
            "seated triceps extension",
            "seated tricep extension",
            "seated overhead triceps extension",
            "seated overhead tricep extension",
            "standing triceps extension",
            "standing overhead triceps extension",
            "two arm overhead extension",
            "french press",
            "cable overhead triceps extension",
            "cable overhead tricep extension",
            "overhead cable triceps extension",
            "overhead cable extension",
            "overhead rope extension",
            "overhead rope triceps extension",
        ],
        "category": "upper_push",
        "camera": _SIDE,
        "equipment": "a single dumbbell held overhead in both hands, palms cupping the underside of the top plate",
        "setting": "a plain gym floor",
        "loop": "pingpong",
        "keyframes": [
            "standing upright, feet hip-width apart, knees soft, single dumbbell held overhead in both hands at full arm extension, elbows locked, upper arms beside the ears",
            "elbows bending about 20 degrees, dumbbell lowering slightly behind the head, upper arms still vertical beside the ears, torso upright, ribs down",
            "elbows bent about 45 degrees, dumbbell behind the top of the head, forearms angled back, upper arms vertical, elbows pointing forward and up",
            "elbows bent about 70 degrees, dumbbell behind the head at ear height, elbows pointing to the ceiling, upper arms unmoved, torso upright",
            "elbows bent about 90 degrees, dumbbell behind the neck, forearms horizontal, elbows narrow and pointing up, no arch in the lower back",
            "bottom position: elbows bent past 90 degrees, dumbbell lowered behind the neck to shoulder-blade height, elbows pointing straight up beside the ears, torso upright",
        ],
        "cue": "Elbows by the ears, lower behind the head, extend fully.",
        "notes": "The upper arms stay vertical beside the ears in every panel; only the forearms hinge at the elbow.",
    },
]
